import json,pathlib,hashlib
r=pathlib.Path(__file__).resolve().parent;root=r.parents[2];h=lambda p:hashlib.sha256(p.read_bytes()).hexdigest()
a=json.loads((r/'original/result.json').read_text());b=json.loads((r/'extended-energy-Ward/result.json').read_text());rows=[]
for i,(p,q)in enumerate(zip(a['probes'],b['probes'])):
 x,y=p['application'],q['application'];assert p['roundtrip']and q['roundtrip'];assert a['selection_observations'][i]['status']=='Unresolved(NoApplicableRule)';assert b['selection_observations'][i]['status']=='Unresolved(NoApplicableRule)'
 rows.append({'ordinal':i,'selection':p['selection'],'baseline_rhs_terms':len(x['rhs']),'extended_rhs_terms':len(y['rhs']),'exact_status_rhs_ordered_conditions_equal':x==y,'baseline_fallback':p['point_fallback'],'extended_fallback':q['point_fallback'],'baseline_conditions':x['conditions'],'extended_conditions':y['conditions'],'extended_proof_uses_added_rows':any(s['source_id'].startswith('extended-polynomial-singleton-energy-Ward-v1/')for rule in q['proof_sources']for s in rule)})
resources=[]
for arm in ['original','extended-energy-Ward']:
 p=r/f'{arm}-resources.json';v=json.loads(p.read_text());assert v['exit_code']==0;resources.append({'arm':arm,'path':str(p.relative_to(r)),'sha256':h(p),'wall_seconds':v['wall_seconds'],'peak_child_rss_kib':v['peak_child_rss_kib']})
proof=pathlib.Path('reports/validation/2026-10-10-singleton-energy-ward-assessment')
inputs=[{'path':str(p),'sha256':h(p)}for p in sorted(proof.rglob('*'))if p.is_file()]
v={'scope':'Validation-only polynomial C1 source extension; original source definitions and measure zeros retained, no reciprocal admission, no imported discovery rules, no numerical periods/closure claim.','corpus_rows':[a['source_count'],b['source_count']],'selection':json.loads((r/'selection.json').read_text()),'geometry':b['geometry'],'old_row_and_guard_equivalence_at_zero_energy_index':True,'retained_zero_domains':True,'native_roundtrips':32,'all_rhs_admitted':a['all_rhs_labels_admitted']and b['all_rhs_labels_admitted'],'rows':rows,'rhs_totals':[sum(x['baseline_rhs_terms']for x in rows),sum(x['extended_rhs_terms']for x in rows)],'exact_empty_rhs_count':[sum(x['baseline_rhs_terms']==0 for x in rows),sum(x['extended_rhs_terms']==0 for x in rows)],'changed_outputs':sum(not x['exact_status_rhs_ordered_conditions_equal']for x in rows),'resources':resources,'theorem_artifact_bindings':inputs,'conclusion':'No change in exact one-step coverage, RHS or ordered conditions for this sample with the added rows appended. This does not prove the identities redundant or rule out a different source order; it provides no practical reason to promote this extension or launch a full pilot.','performance_scope':'Shared-host paired runs include original-program replay selection validation; wall times are not a performance claim.'}
(r/'summary.json').write_text(json.dumps(v,indent=2)+'\n')
(r/'README.md').write_text('The polynomial energy-degree extension of the singleton C1 Ward pair changes none of the 16 tested native reductions when appended to the original 62 sources. Both corpora produce 26 RHS terms in total; nine labels have an exactly empty RHS. Statuses, coefficients and ordered nonzero conditions are identical. All 32 encoded native programs decode and replay, with admitted RHS labels. Every anchored ray misses at cap 1 and takes exact-point fallback.\n\nTwelve labels were chosen lexicographically across pure occupied-energy degree 1 or at least 2, each in bulk and upper-contact sectors. Four further labels lie outside the added C1 or other-energy-zero guards. They come from the actual round004 frontier of the rerouted three-loop cut0 control. The historical native program is replayed only to verify each label is NoApplicableRule, then discarded before fresh source discovery. No old proof is imported or united with a new program.\n\nThe public input and occupied-family builders independently regenerate all factors, roles and routing. They establish exact F6=E0, mass0, mu1, and that medium-dependent F7/F8 must stay at index0. The added sources have own cut1, lower occupation0, completion6<=0, other energy indices0 and original Gram/tail bounds. Their diagonal is D−2−a6; the bulk companion is −E0 H1 and the positive-upper companion is +s E0 H(s+1). The code checks exact agreement of their terms and guards with the existing raw Ward pair at a6=0. The reviewed high-D polynomial origin argument is bound in summary.json; zero domains and the index admission domain are unchanged. This is not reciprocal-energy admission.\n\nBoth arms use the complete original source order, sample seed0, depth3, ray cap1 and point cap1. The extended pair is appended only. A lack of change can reflect first-pivot selection; it does not prove mathematical redundancy or cover every source order. There is no practical benefit in this sample and no production promotion or full-pilot recommendation. Timings include original-program selection replay on a shared host and are not a performance comparison.\n\nSee summary.json, probe.rs, build-binding.json, input-bindings.json, selection.json and both arm result/proof directories for exact evidence. All native proof binaries remain raw. The stdout source count comes from the original record (62) in both arms; result.json correctly records actual source counts 62 and64.\n')
files=[p for p in sorted(r.rglob('*'))if p.is_file()and p.name!='manifest.json'];(r/'manifest.json').write_text(json.dumps({'schema':'sha256-file-manifest-v1','files':[{'path':str(p.relative_to(r)),'bytes':p.stat().st_size,'sha256':h(p)}for p in files]},indent=2)+'\n');print('files',len(files),'manifest',h(r/'manifest.json'),'added-used',sum(x['extended_proof_uses_added_rows']for x in rows))
