$HistoryLength=0;
SetSystemOptions["ParallelOptions" -> "ParallelThreadNumber" -> 1];
threads=("ParallelThreadNumber" /. ("ParallelOptions" /. SystemOptions["ParallelOptions"]));
If[threads =!= 1, Print["thread assertion failed ",threads]; Exit[1]];
root=Environment["RUSTFLOW_PRISM_REFERENCE_DIR"];
masterRules=Get[FileNameJoin[{root,"result-18.wl"}]];
reduction=Get[FileNameJoin[{root,"reduced-combinations.wl"}]];
e=1/5; dim=4-2e;
bubble=Gamma[e] Gamma[1-e]^2/Gamma[2-2e];
masters={bubble Gamma[2e] Gamma[1-2e]^2/Gamma[2-3e], -Gamma[1-e]^3 Gamma[2e-1]/Gamma[3-3e],bubble^2};
exactRules=Thread[reduction["surviving_masters"] -> masters];
refinement=Abs[(N[masters,90]-SetPrecision[N[masters,60],90])/N[masters,90]];
If[Max[refinement]>=10^-50,Print["Gamma precision refinement failed"];Exit[2]];
actual=SetPrecision[reduction["surviving_masters"]/.masterRules,80];
expected=N[masters,80];
errors=Abs[(actual-expected)/expected];
If[!VectorQ[actual,NumericQ]||Max[errors]>=10^-12,Print["independent Gamma comparison failed ",errors];Exit[3]];
actualCoefficients=SetPrecision[reduction["reduced"]/.masterRules,80];
exactCoefficients=reduction["reduced"]/.exactRules;
expectedCoefficients=N[exactCoefficients,80];
coefficientErrors=Abs[(actualCoefficients-expectedCoefficients)/expectedCoefficients];
If[Max[coefficientErrors]>=10^-12,Print["coefficient comparison failed ",coefficientErrors];Exit[4]];
str[x_]:=ToString[x,InputForm];
report=<|"status"->"passed_partial_virtual_reference", "scope"->"Three independent Gamma masters and five prism virtual numerator coefficients at epsilon=1/5; not the complete finite-density integral", "epsilon"->"1/5", "upstream_requested_digits"->18,"upstream_second_precision_completed"->False,"gamma_precision_digits"->{60,90},"master_labels"->(str/@reduction["surviving_masters"]),"master_gamma_expressions"->(str/@masters),"master_values_upstream"->(str/@actual),"master_values_gamma"->(str/@expected),"master_relative_differences"->(str/@errors),"gamma_precision_relative_differences"->(str/@refinement),"coefficient_labels"->reduction["labels"],"coefficient_values_native"->(str/@actualCoefficients),"coefficient_gamma_expressions"->(str/@exactCoefficients),"coefficient_values_gamma_native"->(str/@expectedCoefficients),"coefficient_relative_differences"->(str/@coefficientErrors),"raw_euclidean_conversion"->"C0A,C1A,C0B,C1B multiply (4 Pi)^(-D); CC multiplies -(4 Pi)^(-D), D=18/5", "relative_tolerance"->"1e-12","oracle_records_read"->0,"native_rustflow_predictions_read"->0,"remaining"->"26-digit AMFlow refinement timed out; analytic-index/common-contour finite-density assembly, overlapping endpoint subtractions and Laurent references remain incomplete"|>;
Export[FileNameJoin[{root,"gamma-comparison.json"}],report,"RawJSON"];
Print["GAMMA_CROSSCHECK_PASSED ",Max[errors]," ",Max[coefficientErrors]];
Exit[0];
