//! Restriction of scalars for registered square-root endpoint expansions.
//!
//! For each root monomial m_S = product_{i in S} r_i, adjoin m_S Y.
//! Multiplication uses r_i^2 = R_i and differentiation adds
//! sum_{i in S} R_i'/(2 R_i) on the diagonal. This is an exact rational
//! connection, so the existing Frobenius engine supplies powers, logarithms,
//! resonances and coupled blocks. No second algebra or series engine is needed.
use super::*;
use crate::frobenius::{FrobeniusBasis, PreparedFrobenius};

/// Rational connection obtained from the root monomials generated by the kernel
/// and epsilon coefficients. Rows are ordered by monomial, epsilon offset, component.
/// The root-free rows come first. The lift is exact; its numerical solution is
/// physical only after matching a boundary with consistent root signs.
#[derive(Clone, Debug)]
pub struct RationalAlgebraicSystem {
    source: AlgebraicSystem,
    rational: DifferentialSystem,
    size: usize,
    count: usize,
    monomials: Vec<usize>,
}

/// Shared exact endpoint preparation. Local expansions are centered at zero;
/// [`AlgebraicSystem::pullback_coordinate`] centers finite endpoints or infinity.
#[derive(Clone, Debug)]
pub struct PreparedAlgebraicFrobenius {
    lifted: RationalAlgebraicSystem,
    prepared: PreparedFrobenius,
}

/// Matched local power/logarithm series on a selected algebraic sheet.
/// Working precision and truncation order are not achieved-accuracy evidence:
/// independently rematch at increased precision/order before caching a boundary.
#[derive(Clone, Debug)]
pub struct AlgebraicEndpointExpansion {
    basis: FrobeniusBasis,
    constants: Vec<C>,
    size: usize,
    count: usize,
    leading: i32,
    matching_branches: BranchState,
    variable: Symbol,
    regular_domain_guards: Vec<Atom>,
}

impl AlgebraicSystem {
    /// Substitute x = map(z), including its exact Jacobian. Use `map = c+z`
    /// for a finite endpoint and `map = 1/z` for infinity. This changes the
    /// coordinate; it does not choose a physical contour or a root sheet.
    pub fn pullback_coordinate(&self, variable: Symbol, map: &Atom) -> Result<Self> {
        self.validate()?;
        if variable == imaginary_parameter() || self.roots.iter().any(|r| r.symbol == variable) {
            return Err(Error::InvalidInput(
                "local coordinate collides with a root or the imaginary unit".into(),
            ));
        }
        rational(
            map,
            &BTreeSet::from([Atom::var(variable), Atom::var(imaginary_parameter())]),
        )?;
        let jacobian = map.derivative(variable);
        if jacobian.is_zero() {
            return Err(Error::InvalidInput(
                "local coordinate map must be nonconstant".into(),
            ));
        }
        let rules = BTreeMap::from([(Atom::var(self.system.variable), map.clone())]);
        // Collect before substitution/cancellation, so a removable source norm
        // pole cannot disappear from the regular matching domain.
        let mut conditions = registered_domain_conditions(
            &self
                .system
                .matrices
                .iter()
                .flatten()
                .flatten()
                .cloned()
                .collect::<Vec<_>>(),
            &self.roots,
            &BTreeSet::from([self.system.variable]),
        )?;
        conditions.extend(self.nonzero_conditions.clone());
        let mut target_conditions = conditions
            .iter()
            .map(|a| substitute(a, &rules))
            .collect::<Vec<_>>();
        target_conditions.extend(crate::physical_conditions::rational_denominator_conditions(
            std::slice::from_ref(map),
            &BTreeSet::from([variable, imaginary_parameter()]),
        )?);
        let result = Self {
            system: EpsilonSystem {
                variable,
                matrices: self
                    .system
                    .matrices
                    .iter()
                    .map(|matrix| {
                        matrix
                            .iter()
                            .map(|row| {
                                row.iter()
                                    .map(|a| substitute(a, &rules) * &jacobian)
                                    .collect()
                            })
                            .collect()
                    })
                    .collect(),
            },
            roots: self
                .roots
                .iter()
                .map(|root| SquareRoot {
                    symbol: root.symbol,
                    radicand: substitute(&root.radicand, &rules),
                })
                .collect(),
            nonzero_conditions: target_conditions,
        };
        result.validate()?;
        Ok(result)
    }

    /// Exact restriction of scalars. `max_dimension` bounds the dense lifted
    /// matrix dimension n * epsilon_orders * generated_monomials before
    /// allocation. The number of generated monomials is at most 2^roots. This
    /// adapter is intended for local singular charts; regular transport retains
    /// its sparse native-root representation.
    pub fn rational_lift(
        &self,
        max_dimension: usize,
        context: &RunContext,
    ) -> Result<RationalAlgebraicSystem> {
        context.cancellation.check()?;
        self.validate()?;
        let size = self.system.matrices[0].len();
        let count = self.system.matrices.len();
        if self.roots.len() >= usize::BITS as usize {
            return Err(Error::Limit(
                "root registry exceeds the endpoint bit-mask width".into(),
            ));
        }
        let stride = size
            .checked_mul(count)
            .ok_or_else(|| Error::Limit("epsilon lift dimension overflows".into()))?;
        let checked_dimension = |monomials: usize| {
            stride
                .checked_mul(monomials)
                .filter(|&n| n <= max_dimension && n.checked_mul(n).is_some())
                .ok_or_else(|| {
                    Error::Limit(format!(
                        "algebraic Frobenius lift exceeds dimension limit {max_dimension}"
                    ))
                })
        };
        checked_dimension(1)?;
        let mut allowed = BTreeSet::from([
            Atom::var(self.system.variable),
            Atom::var(imaginary_parameter()),
        ]);
        allowed.extend(self.roots.iter().map(|r| Atom::var(r.symbol)));
        // Only the subgroup generated by root monomials actually present in A
        // is needed. An unused radical, or many roots appearing only through
        // their product, must not cause unnecessary exponential growth.
        let mut monomials = vec![0];
        let mut monomial_indices = BTreeMap::from([(0, 0)]);
        let mut terms = Vec::new();
        for (offset, source) in self.system.matrices.iter().enumerate() {
            for (i, row) in source.iter().enumerate() {
                for (j, entry) in row.iter().enumerate() {
                    context.cancellation.check()?;
                    let normalized = normalized_root_entry(entry, &self.roots, &allowed)?;
                    for (indices, coefficient) in normalized.terms {
                        let term_mask = indices.iter().fold(0, |mask, i| mask | 1 << i);
                        if !monomial_indices.contains_key(&term_mask) {
                            let old_count = monomials.len();
                            checked_dimension(old_count.checked_mul(2).ok_or_else(|| {
                                Error::Limit("root subgroup dimension overflows".into())
                            })?)?;
                            for index in 0..old_count {
                                let mask = monomials[index] ^ term_mask;
                                monomial_indices.insert(mask, monomials.len());
                                monomials.push(mask);
                            }
                        }
                        terms.push((offset, i, j, term_mask, decoded(&coefficient)));
                    }
                }
            }
        }
        let dimension = checked_dimension(monomials.len())?;
        let mut matrix = vec![vec![Atom::new(); dimension]; dimension];
        for (offset, i, j, term_mask, coefficient) in terms {
            context.cancellation.check()?;
            for (monomial, &mask) in monomials.iter().enumerate() {
                let mut factor = coefficient.clone();
                for (index, root) in self.roots.iter().enumerate() {
                    if mask & term_mask & (1 << index) != 0 {
                        factor *= &root.radicand;
                    }
                }
                factor = factor.together().cancel();
                let target = monomial_indices[&(mask ^ term_mask)];
                for k in offset..count {
                    matrix[monomial * stride + k * size + i]
                        [target * stride + (k - offset) * size + j] += &factor;
                }
            }
        }
        for (monomial, &mask) in monomials.iter().enumerate() {
            context.cancellation.check()?;
            let derivative = self
                .roots
                .iter()
                .enumerate()
                .filter(|(i, _)| mask & (1 << i) != 0)
                .fold(Atom::new(), |sum, (_, r)| {
                    sum + r.radicand.derivative(self.system.variable) / (&r.radicand * 2)
                });
            for k in 0..stride {
                matrix[monomial * stride + k][monomial * stride + k] += &derivative;
            }
        }
        for row in &mut matrix {
            context.cancellation.check()?;
            for entry in row {
                *entry = decoded(entry);
            }
        }
        Ok(RationalAlgebraicSystem {
            source: self.clone(),
            rational: DifferentialSystem {
                variable: self.system.variable,
                matrix,
            },
            size,
            count,
            monomials,
        })
    }

    /// Prepare all Puiseux/logarithmic sectors through the existing rational
    /// Frobenius engine. Its indicial-root and Fuchsian-normalization limits
    /// remain explicit typed errors; irregular exponential sectors are rejected.
    pub fn prepare_frobenius(
        &self,
        max_dimension: usize,
        context: &RunContext,
    ) -> Result<PreparedAlgebraicFrobenius> {
        let lifted = self.rational_lift(max_dimension, context)?;
        let prepared = lifted.rational.prepare_frobenius(context)?;
        Ok(PreparedAlgebraicFrobenius { lifted, prepared })
    }
}

impl RationalAlgebraicSystem {
    pub fn system(&self) -> &DifferentialSystem {
        &self.rational
    }

    /// Exact monomials in the order used by the rational row blocks.
    pub fn root_monomials(&self) -> Vec<Atom> {
        self.monomials
            .iter()
            .map(|&mask| {
                self.source
                    .roots
                    .iter()
                    .enumerate()
                    .filter(|(i, _)| mask & (1 << i) != 0)
                    .fold(Atom::num(1), |value, (_, root)| {
                        value * Atom::var(root.symbol)
                    })
            })
            .collect()
    }

    /// Recover the original epsilon coefficient rows after rational transport.
    /// The input must descend from a consistently lifted boundary; this
    /// projection does not certify its branch, accuracy, or domain.
    pub fn project_boundary(
        &self,
        boundary: &BoundaryData,
        leading: i32,
    ) -> Result<EpsilonBoundary> {
        if boundary.values.len() != self.rational.matrix.len()
            || !boundary.point.re.is_finite()
            || !boundary.point.im.is_finite()
            || boundary
                .values
                .iter()
                .any(|a| !a.re.is_finite() || !a.im.is_finite())
        {
            return Err(Error::InvalidInput(
                "lifted boundary dimensions or nonfinite values".into(),
            ));
        }
        leading
            .checked_add(self.count as i32 - 1)
            .ok_or_else(|| Error::InvalidInput("epsilon power range overflows".into()))?;
        Ok(EpsilonBoundary {
            point: boundary.point.clone(),
            leading,
            coefficients: boundary.values[..self.size * self.count]
                .chunks(self.size)
                .map(<[C]>::to_vec)
                .collect(),
        })
    }

    /// Lift a regular matching boundary using the same exact-radicand seeding
    /// and conservative domain checks as regular algebraic transport.
    pub fn lift_boundary(
        &self,
        boundary: &EpsilonBoundary,
        seeds: &BTreeMap<Symbol, RootSeed>,
        p: Precision,
    ) -> Result<(BoundaryData, BranchState)> {
        let (boundary, branches, _) = self.lift_boundary_data(boundary, seeds, p)?;
        Ok((boundary, branches))
    }

    fn lift_boundary_data(
        &self,
        boundary: &EpsilonBoundary,
        seeds: &BTreeMap<Symbol, RootSeed>,
        p: Precision,
    ) -> Result<(BoundaryData, BranchState, Vec<Atom>)> {
        if boundary.coefficients.len() != self.count
            || boundary
                .coefficients
                .iter()
                .any(|row| row.len() != self.size)
            || !p.finite(&boundary.point)
            || boundary.coefficients.iter().flatten().any(|a| !p.finite(a))
        {
            return Err(Error::InvalidInput(
                "algebraic endpoint boundary dimensions or nonfinite values".into(),
            ));
        }
        boundary
            .leading
            .checked_add(self.count as i32 - 1)
            .ok_or_else(|| Error::InvalidInput("epsilon power range overflows".into()))?;
        let compiled = self.source.compile(p)?;
        let flat = BoundaryData {
            point: boundary.point.clone(),
            values: boundary.coefficients.iter().flatten().cloned().collect(),
        };
        let branches = AlgebraicRun {
            compiled: &compiled,
            seeds,
        }
        .initial_state(&flat)?;
        let mut values = Vec::with_capacity(self.rational.matrix.len());
        for &mask in &self.monomials {
            let factor = branches
                .roots
                .iter()
                .enumerate()
                .filter(|(i, _)| mask & (1 << i) != 0)
                .fold(p.i(1), |value, (_, (_, root))| p.mul(&value, root));
            values.extend(flat.values.iter().map(|value| p.mul(&factor, value)));
        }
        let mut guards = compiled.domain_guards.clone();
        guards.extend(compiled.pole_polynomials.clone());
        guards.sort();
        guards.dedup();
        Ok((
            BoundaryData {
                point: flat.point,
                values,
            },
            branches,
            guards,
        ))
    }
}

impl PreparedAlgebraicFrobenius {
    pub fn lifted_system(&self) -> &RationalAlgebraicSystem {
        &self.lifted
    }
    pub fn rational_preparation(&self) -> &PreparedFrobenius {
        &self.prepared
    }

    /// Match a regular boundary in the local Frobenius convergence domain.
    /// `winding` is the branch of log(x) at that point. Boundary root signs
    /// select the algebraic sheet; subsequent evaluation uses the same local
    /// logarithm convention. No global physical prescription is inferred.
    #[allow(clippy::too_many_arguments)]
    pub fn match_boundary(
        &self,
        boundary: &EpsilonBoundary,
        seeds: &BTreeMap<Symbol, RootSeed>,
        p: Precision,
        order: usize,
        winding: i32,
        context: &RunContext,
    ) -> Result<AlgebraicEndpointExpansion> {
        context.cancellation.check()?;
        let (boundary_lift, matching_branches, regular_domain_guards) =
            self.lifted.lift_boundary_data(boundary, seeds, p)?;
        let basis = self
            .prepared
            .evaluate(p, &Default::default(), order, context)?;
        let constants = crate::numeric::solve(
            p,
            basis.evaluate_with_winding(&boundary.point, &Default::default(), winding)?,
            boundary_lift.values,
        )?;
        context.cancellation.check()?;
        Ok(AlgebraicEndpointExpansion {
            basis,
            constants,
            size: self.lifted.size,
            count: self.lifted.count,
            leading: boundary.leading,
            matching_branches,
            variable: self.lifted.source.system.variable,
            regular_domain_guards,
        })
    }
}

impl AlgebraicEndpointExpansion {
    pub fn matching_branches(&self) -> &BranchState {
        &self.matching_branches
    }
    pub fn basis(&self) -> &FrobeniusBasis {
        &self.basis
    }
    pub fn constants(&self) -> &[C] {
        &self.constants
    }

    /// Evaluate a nonzero local coordinate. Fractional powers and logarithms
    /// share the requested winding. The caller must stay inside the local
    /// convergence disk; precision/order refinement is required for evidence.
    pub fn evaluate(&self, point: &C, winding: i32) -> Result<EpsilonBoundary> {
        let rules = BTreeMap::from([(
            Atom::var(self.variable),
            exact_point(self.basis.precision, point)?,
        )]);
        if self
            .regular_domain_guards
            .iter()
            .any(|a| decoded(&substitute(a, &rules)).is_zero())
        {
            return Err(Error::InvalidInput("algebraic endpoint series evaluation lies on a retained singularity; use coefficient_limits at the expansion center".into()));
        }
        let matrix = self
            .basis
            .evaluate_with_winding(point, &Default::default(), winding)?;
        let p = self.basis.precision;
        let values = matrix
            .iter()
            .take(self.size * self.count)
            .map(|row| {
                row.iter()
                    .zip(&self.constants)
                    .fold(p.zero(), |sum, (a, b)| p.add(&sum, &p.mul(a, b)))
            })
            .collect::<Vec<_>>();
        Ok(EpsilonBoundary {
            point: point.clone(),
            leading: self.leading,
            coefficients: values.chunks(self.size).map(<[C]>::to_vec).collect(),
        })
    }

    /// Finite endpoint limits of the retained epsilon coefficients, projecting
    /// only original components. Divergent auxiliary rows are irrelevant.
    /// These limits are taken after epsilon expansion: symbolic dimensional
    /// sectors cannot be selected from this hierarchy. In particular, logarithms
    /// from an x^epsilon sector return a divergence error. No small-mass
    /// substitution or achieved-accuracy certification is performed.
    pub fn coefficient_limits(&self) -> Result<Vec<Vec<C>>> {
        let n = self.basis.columns.len();
        let values = (0..self.size * self.count)
            .map(|component| {
                let weights = (0..n)
                    .map(|j| Atom::num(i64::from(component == j)))
                    .collect::<Vec<_>>();
                crate::engine::project_limit(
                    &self.basis,
                    &self.constants,
                    &weights,
                    symbol!("symbolica_amflow::algebraic_endpoint_epsilon"),
                    symbol!("symbolica_amflow::algebraic_endpoint_projection"),
                    &Default::default(),
                )
            })
            .collect::<Result<Vec<_>>>()?;
        Ok(values.chunks(self.size).map(<[C]>::to_vec).collect())
    }
}
