//! Restriction of scalars for registered square-root endpoint expansions.
//!
//! For each root monomial m_S = product_{i in S} r_i, adjoin m_S Y.
//! Multiplication uses r_i^2 = R_i and differentiation adds
//! sum_{i in S} R_i'/(2 R_i) on the diagonal. This is an exact rational
//! connection, so the existing Frobenius engine supplies powers, logarithms,
//! resonances and coupled blocks. No second algebra or series engine is needed.
use super::*;
use crate::frobenius::{FrobeniusBasis, PreparedFrobenius};
use symbolica::domains::float::{ComplexBall, FloatField, RealBall, RoundingDirection};
use symbolica::tensors::matrix::Matrix;

mod constrained;
mod sheet;
mod sheet_germ;
#[cfg(test)]
mod sheet_tests;

pub(crate) struct EndpointLinearMap {
    pub(crate) values: Vec<Vec<C>>,
    pub(crate) arithmetic_errors: Vec<Vec<Float>>,
}

#[cfg(test)]
mod endpoint_map_tests {
    use super::*;

    #[test]
    fn normalization_padding_does_not_extend_the_known_nonpositive_prefix() {
        let z = symbol!("endpoint_order_test::z");
        let source = AlgebraicSystem::ordinary(
            DifferentialSystem {
                variable: z,
                matrix: vec![
                    vec![Atom::new(), Atom::var(z).pow(-21)],
                    vec![Atom::new(), Atom::new()],
                ],
            },
            Vec::new(),
        );
        let context = RunContext::default();
        let prepared = source.prepare_frobenius(4, &context).unwrap();
        let p = Precision::decimal(80).unwrap();
        let point = p.rational(&Rational::from((1, 16)));
        assert!(
            prepared
                .endpoint_map(&point, &Default::default(), p, 8, 0, &context)
                .unwrap()
                .is_none()
        );
        assert!(matches!(
            prepared.endpoint_map(&point, &Default::default(), p, 40, 0, &context),
            Err(Error::Accuracy(_))
        ));
    }
}

/// Rational connection obtained from the root monomials generated by the kernel
/// and epsilon coefficients. Rows are ordered by monomial, epsilon offset, component.
/// The root-free rows come first. The lift is exact; its numerical solution is
/// physical only after matching a boundary with consistent root signs.
#[derive(Clone, Debug)]
pub struct RationalAlgebraicSystem {
    source: AlgebraicSystem,
    rational: DifferentialSystem,
    size: usize,
    count: usize,
    monomials: Vec<usize>,
}

/// Shared exact endpoint preparation. Local expansions are centered at zero;
/// [`AlgebraicSystem::pullback_coordinate`] centers finite endpoints or infinity.
#[derive(Clone, Debug)]
pub struct PreparedAlgebraicFrobenius {
    lifted: RationalAlgebraicSystem,
    prepared: PreparedFrobenius,
}

/// Matched local power/logarithm series on a selected algebraic sheet.
/// Working precision and truncation order are not achieved-accuracy evidence:
/// independently rematch at increased precision/order before caching a boundary.
#[derive(Clone, Debug)]
pub struct AlgebraicEndpointExpansion {
    basis: FrobeniusBasis,
    constants: Vec<C>,
    size: usize,
    count: usize,
    leading: i32,
    matching_branches: BranchState,
    variable: Symbol,
    regular_domain_guards: Vec<Atom>,
}

impl AlgebraicSystem {
    /// Substitute x = map(z), including its exact Jacobian. Use `map = c+z`
    /// for a finite endpoint and `map = 1/z` for infinity. This changes the
    /// coordinate; it does not choose a physical contour or a root sheet.
    pub fn pullback_coordinate(&self, variable: Symbol, map: &Atom) -> Result<Self> {
        self.validate()?;
        if variable == imaginary_parameter() || self.roots.iter().any(|r| r.symbol == variable) {
            return Err(Error::InvalidInput(
                "local coordinate collides with a root or the imaginary unit".into(),
            ));
        }
        rational(
            map,
            &BTreeSet::from([Atom::var(variable), Atom::var(imaginary_parameter())]),
        )?;
        let jacobian = map.derivative(variable);
        if jacobian.is_zero() {
            return Err(Error::InvalidInput(
                "local coordinate map must be nonconstant".into(),
            ));
        }
        let rules = BTreeMap::from([(Atom::var(self.system.variable), map.clone())]);
        // Collect before substitution/cancellation, so a removable source norm
        // pole cannot disappear from the regular matching domain.
        let mut conditions = registered_domain_conditions(
            &self
                .system
                .matrices
                .iter()
                .flatten()
                .flatten()
                .cloned()
                .collect::<Vec<_>>(),
            &self.roots,
            &BTreeSet::from([self.system.variable]),
        )?;
        conditions.extend(self.nonzero_conditions.clone());
        let mut target_conditions = conditions
            .iter()
            .map(|a| substitute(a, &rules))
            .collect::<Vec<_>>();
        target_conditions.extend(crate::physical_conditions::rational_denominator_conditions(
            std::slice::from_ref(map),
            &BTreeSet::from([variable, imaginary_parameter()]),
        )?);
        let result = Self {
            system: EpsilonSystem {
                variable,
                matrices: self
                    .system
                    .matrices
                    .iter()
                    .map(|matrix| {
                        matrix
                            .iter()
                            .map(|row| {
                                row.iter()
                                    .map(|a| substitute(a, &rules) * &jacobian)
                                    .collect()
                            })
                            .collect()
                    })
                    .collect(),
            },
            roots: self
                .roots
                .iter()
                .map(|root| SquareRoot {
                    symbol: root.symbol,
                    radicand: substitute(&root.radicand, &rules),
                })
                .collect(),
            nonzero_conditions: target_conditions,
        };
        result.validate()?;
        Ok(result)
    }

    /// Exact restriction of scalars. `max_dimension` bounds the dense lifted
    /// matrix dimension n * epsilon_orders * generated_monomials before
    /// allocation. The number of generated monomials is at most 2^roots. This
    /// adapter is intended for local singular charts; regular transport retains
    /// its sparse native-root representation.
    pub fn rational_lift(
        &self,
        max_dimension: usize,
        context: &RunContext,
    ) -> Result<RationalAlgebraicSystem> {
        context.cancellation.check()?;
        self.validate()?;
        let size = self.system.matrices[0].len();
        let count = self.system.matrices.len();
        if self.roots.len() >= usize::BITS as usize {
            return Err(Error::Limit(
                "root registry exceeds the endpoint bit-mask width".into(),
            ));
        }
        let stride = size
            .checked_mul(count)
            .ok_or_else(|| Error::Limit("epsilon lift dimension overflows".into()))?;
        let checked_dimension = |monomials: usize| {
            stride
                .checked_mul(monomials)
                .filter(|&n| n <= max_dimension && n.checked_mul(n).is_some())
                .ok_or_else(|| {
                    Error::Limit(format!(
                        "algebraic Frobenius lift exceeds dimension limit {max_dimension}"
                    ))
                })
        };
        checked_dimension(1)?;
        let mut allowed = BTreeSet::from([
            Atom::var(self.system.variable),
            Atom::var(imaginary_parameter()),
        ]);
        allowed.extend(self.roots.iter().map(|r| Atom::var(r.symbol)));
        // Only the subgroup generated by root monomials actually present in A
        // is needed. An unused radical, or many roots appearing only through
        // their product, must not cause unnecessary exponential growth.
        let mut monomials = vec![0];
        let mut monomial_indices = BTreeMap::from([(0, 0)]);
        let mut terms = Vec::new();
        for (offset, source) in self.system.matrices.iter().enumerate() {
            for (i, row) in source.iter().enumerate() {
                for (j, entry) in row.iter().enumerate() {
                    context.cancellation.check()?;
                    let normalized = normalized_root_entry(entry, &self.roots, &allowed)?;
                    for (indices, coefficient) in normalized.terms {
                        let term_mask = indices.iter().fold(0, |mask, i| mask | 1 << i);
                        if !monomial_indices.contains_key(&term_mask) {
                            let old_count = monomials.len();
                            checked_dimension(old_count.checked_mul(2).ok_or_else(|| {
                                Error::Limit("root subgroup dimension overflows".into())
                            })?)?;
                            for index in 0..old_count {
                                let mask = monomials[index] ^ term_mask;
                                monomial_indices.insert(mask, monomials.len());
                                monomials.push(mask);
                            }
                        }
                        terms.push((offset, i, j, term_mask, decoded(&coefficient)));
                    }
                }
            }
        }
        let dimension = checked_dimension(monomials.len())?;
        let mut matrix = vec![vec![Atom::new(); dimension]; dimension];
        for (offset, i, j, term_mask, coefficient) in terms {
            context.cancellation.check()?;
            for (monomial, &mask) in monomials.iter().enumerate() {
                let factor = (coefficient.clone()
                    * intersection_factor(&self.roots, mask, term_mask))
                .together()
                .cancel();
                let target = monomial_indices[&(mask ^ term_mask)];
                for k in offset..count {
                    matrix[monomial * stride + k * size + i]
                        [target * stride + (k - offset) * size + j] += &factor;
                }
            }
        }
        for (monomial, &mask) in monomials.iter().enumerate() {
            context.cancellation.check()?;
            let derivative = self
                .roots
                .iter()
                .enumerate()
                .filter(|(i, _)| mask & (1 << i) != 0)
                .fold(Atom::new(), |sum, (_, r)| {
                    sum + r.radicand.derivative(self.system.variable) / (&r.radicand * 2)
                });
            for k in 0..stride {
                matrix[monomial * stride + k][monomial * stride + k] += &derivative;
            }
        }
        for row in &mut matrix {
            context.cancellation.check()?;
            for entry in row {
                *entry = decoded(entry);
            }
        }
        Ok(RationalAlgebraicSystem {
            source: self.clone(),
            rational: DifferentialSystem {
                variable: self.system.variable,
                matrix,
            },
            size,
            count,
            monomials,
        })
    }

    /// Prepare all Puiseux/logarithmic sectors through the existing rational
    /// Frobenius engine. Its indicial-root and Fuchsian-normalization limits
    /// remain explicit typed errors; irregular exponential sectors are rejected.
    pub fn prepare_frobenius(
        &self,
        max_dimension: usize,
        context: &RunContext,
    ) -> Result<PreparedAlgebraicFrobenius> {
        let lifted = self.rational_lift(max_dimension, context)?;
        let prepared = lifted.rational.prepare_frobenius(context)?;
        Ok(PreparedAlgebraicFrobenius { lifted, prepared })
    }
}

/// Native normalized-root monomials multiply by XOR with intersection squares.
/// Both connection construction and exact sheet action use this same owner.
fn intersection_factor(roots: &[SquareRoot], left: usize, right: usize) -> Atom {
    roots
        .iter()
        .enumerate()
        .filter(|(i, _)| left & right & (1 << i) != 0)
        .fold(Atom::one(), |a, (_, root)| a * &root.radicand)
        .together()
        .cancel()
}

impl RationalAlgebraicSystem {
    pub fn system(&self) -> &DifferentialSystem {
        &self.rational
    }

    /// Exact monomials in the order used by the rational row blocks.
    pub fn root_monomials(&self) -> Vec<Atom> {
        self.monomials
            .iter()
            .map(|&mask| {
                self.source
                    .roots
                    .iter()
                    .enumerate()
                    .filter(|(i, _)| mask & (1 << i) != 0)
                    .fold(Atom::num(1), |value, (_, root)| {
                        value * Atom::var(root.symbol)
                    })
            })
            .collect()
    }

    /// Recover the original epsilon coefficient rows after rational transport.
    /// The input must descend from a consistently lifted boundary; this
    /// projection does not certify its branch, accuracy, or domain.
    pub fn project_boundary(
        &self,
        boundary: &BoundaryData,
        leading: i32,
    ) -> Result<EpsilonBoundary> {
        if boundary.values.len() != self.rational.matrix.len()
            || !boundary.point.re.is_finite()
            || !boundary.point.im.is_finite()
            || boundary
                .values
                .iter()
                .any(|a| !a.re.is_finite() || !a.im.is_finite())
        {
            return Err(Error::InvalidInput(
                "lifted boundary dimensions or nonfinite values".into(),
            ));
        }
        leading
            .checked_add(self.count as i32 - 1)
            .ok_or_else(|| Error::InvalidInput("epsilon power range overflows".into()))?;
        Ok(EpsilonBoundary {
            point: boundary.point.clone(),
            leading,
            coefficients: boundary.values[..self.size * self.count]
                .chunks(self.size)
                .map(<[C]>::to_vec)
                .collect(),
        })
    }

    /// Lift a regular matching boundary using the same exact-radicand seeding
    /// and conservative domain checks as regular algebraic transport.
    pub fn lift_boundary(
        &self,
        boundary: &EpsilonBoundary,
        seeds: &BTreeMap<Symbol, RootSeed>,
        p: Precision,
    ) -> Result<(BoundaryData, BranchState)> {
        let (boundary, branches, _) = self.lift_boundary_data(boundary, seeds, p)?;
        Ok((boundary, branches))
    }

    fn lift_boundary_data(
        &self,
        boundary: &EpsilonBoundary,
        seeds: &BTreeMap<Symbol, RootSeed>,
        p: Precision,
    ) -> Result<(BoundaryData, BranchState, Vec<Atom>)> {
        if boundary.coefficients.len() != self.count
            || boundary
                .coefficients
                .iter()
                .any(|row| row.len() != self.size)
            || !p.finite(&boundary.point)
            || boundary.coefficients.iter().flatten().any(|a| !p.finite(a))
        {
            return Err(Error::InvalidInput(
                "algebraic endpoint boundary dimensions or nonfinite values".into(),
            ));
        }
        boundary
            .leading
            .checked_add(self.count as i32 - 1)
            .ok_or_else(|| Error::InvalidInput("epsilon power range overflows".into()))?;
        let compiled = self.source.compile(p)?;
        let flat = BoundaryData {
            point: boundary.point.clone(),
            values: boundary.coefficients.iter().flatten().cloned().collect(),
        };
        let branches = AlgebraicRun {
            compiled: &compiled,
            seeds,
        }
        .initial_state(&flat)?;
        let mut values = Vec::with_capacity(self.rational.matrix.len());
        for &mask in &self.monomials {
            let factor = branches
                .roots
                .iter()
                .enumerate()
                .filter(|(i, _)| mask & (1 << i) != 0)
                .fold(p.i(1), |value, (_, (_, root))| p.mul(&value, root));
            values.extend(flat.values.iter().map(|value| p.mul(&factor, value)));
        }
        let mut guards = compiled.domain_guards.clone();
        guards.extend(compiled.pole_polynomials.clone());
        guards.sort();
        guards.dedup();
        Ok((
            BoundaryData {
                point: flat.point,
                values,
            },
            branches,
            guards,
        ))
    }
}

impl PreparedAlgebraicFrobenius {
    pub fn lifted_system(&self) -> &RationalAlgebraicSystem {
        &self.lifted
    }
    pub fn rational_preparation(&self) -> &PreparedFrobenius {
        &self.prepared
    }

    /// Original source/root domains, retained independently of the rational lift.
    pub(crate) fn endpoint_guards(&self, p: Precision) -> Result<Vec<Atom>> {
        let source = self.lifted.source.compile(p)?;
        let mut guards = source.domain_guards;
        guards.extend(source.pole_polynomials);
        guards.extend(self.prepared.nonzero_conditions().iter().cloned());
        Ok(guards)
    }

    /// One native inverse serves every physical unit direction. The matrix
    /// residual bounds arithmetic for the stored numerical matching matrix;
    /// independent precision/order profiles still estimate recurrence error.
    #[allow(clippy::too_many_arguments)]
    pub(crate) fn endpoint_map(
        &self,
        point: &C,
        seeds: &BTreeMap<Symbol, RootSeed>,
        p: Precision,
        order: usize,
        winding: i32,
        context: &RunContext,
    ) -> Result<Option<EndpointLinearMap>> {
        context.cancellation.check()?;
        let physical = self.lifted.size * self.lifted.count;
        let zero = EpsilonBoundary {
            point: point.clone(),
            leading: 0,
            coefficients: vec![vec![p.zero(); self.lifted.size]; self.lifted.count],
        };
        let (_, branches, _) = self.lifted.lift_boundary_data(&zero, seeds, p)?;
        let basis = self
            .prepared
            .evaluate_endpoint(p, &Default::default(), order, context)
            .map_err(|error| match error {
                Error::Numerical(message) => Error::InsufficientPrecision {
                    minimum_bits: p.bits.saturating_mul(2),
                    context: format!("endpoint recurrence: {message}"),
                },
                error => error,
            })?;
        let n = basis.columns.len();
        let mut exponents = Vec::with_capacity(n);
        for column in &basis.columns {
            let AtomView::Num(exponent) = column.exponent.as_view() else {
                return Err(Error::Unsupported("finite coefficient endpoint requires exact rational exponents; dimensional-sector projection is separate".into()));
            };
            let symbolica::coefficient::Coefficient::Complex(exponent) =
                exponent.get_coeff_view().to_owned()
            else {
                return Err(Error::Unsupported("nonrational endpoint exponent".into()));
            };
            if !exponent.im.is_zero() {
                return Err(Error::Unsupported("complex endpoint exponent".into()));
            }
            // Do this before matching: a truncated normalization can even
            // erase a matrix row and produce a spurious singular inverse.
            // Padding does not extend the uniformly known Laurent prefix.
            if &exponent.re + &Rational::from(order + 1) <= Rational::zero() {
                return Ok(None);
            }
            exponents.push(exponent.re);
        }
        let field = FloatField::from_rep(p.zero());
        let matching = Matrix::from_nested_vec(
            basis.evaluate_with_winding(point, &Default::default(), winding)?,
            field,
        )
        .map_err(Error::Numerical)?;
        context.cancellation.check()?;
        let (b, inverse_error) = conditioned_inverse(&matching, p, context)?;
        let exact = |a: &C| stored_ball(a, p);
        let upper = |a: &ComplexBall| ball_upper(a, p);
        let ball_field = FloatField::from_rep(exact(&p.zero()));
        let mut lift = Matrix::new(n as u32, physical as u32, ball_field.clone());
        for (block, &mask) in self.lifted.monomials.iter().enumerate() {
            let factor = branches
                .roots
                .iter()
                .enumerate()
                .filter(|(i, _)| mask & (1 << i) != 0)
                .fold(p.i(1), |value, (_, (_, root))| p.mul(&value, root));
            for j in 0..physical {
                lift[((block * physical + j) as u32, j as u32)] = exact(&factor);
            }
        }
        let constants = &b * &lift;
        let mut finite = Matrix::new(physical as u32, n as u32, ball_field.clone());
        let mut divergent = BTreeMap::<(Rational, usize), Matrix<FloatField<ComplexBall>>>::new();
        for (j, column) in basis.columns.iter().enumerate() {
            for (k, logs) in column.coefficients.iter().enumerate() {
                let power = &exponents[j] + &Rational::from(k);
                if power > Rational::zero() {
                    break;
                }
                for (log, row) in logs.iter().enumerate() {
                    let matrix = if power.is_zero() && log == 0 {
                        &mut finite
                    } else {
                        divergent.entry((power.clone(), log)).or_insert_with(|| {
                            Matrix::new(physical as u32, n as u32, ball_field.clone())
                        })
                    };
                    for (i, value) in row.iter().take(physical).enumerate() {
                        matrix[(i as u32, j as u32)] = exact(value);
                    }
                }
            }
        }
        for matrix in divergent.values() {
            context.cancellation.check()?;
            let coefficient = matrix * &constants;
            for i in 0..physical {
                for j in 0..physical {
                    let value = &coefficient[(i as u32, j as u32)];
                    if !value.re.center.is_zero()
                        || !value.im.center.is_zero()
                        || !value.re.radius.is_zero()
                        || !value.im.radius.is_zero()
                    {
                        return Err(Error::Accuracy("an independent boundary perturbation has a divergent or unresolved endpoint sector; correlated/constrained-sector evidence is required".into()));
                    }
                }
            }
        }
        let transfer = &finite * &constants;
        let mut values = vec![vec![p.zero(); physical]; physical];
        let mut errors = vec![vec![p.real(0); physical]; physical];
        for i in 0..physical {
            context.cancellation.check()?;
            let row_norm = (0..n).fold(p.real(0), |sum, j| {
                sum.add_round(
                    &upper(&finite[(i as u32, j as u32)]),
                    p.bits,
                    RoundingDirection::Up,
                )
            });
            for j in 0..physical {
                let column_norm = (0..n)
                    .map(|k| upper(&lift[(k as u32, j as u32)]))
                    .reduce(|a, b| if a > b { a } else { b })
                    .unwrap_or_else(|| p.real(0));
                let value = &transfer[(i as u32, j as u32)];
                values[i][j] = C::new(value.re.center.clone(), value.im.center.clone());
                errors[i][j] = value
                    .re
                    .radius
                    .add_round(&value.im.radius, p.bits, RoundingDirection::Up)
                    .add_round(
                        &row_norm
                            .mul_round(&inverse_error, p.bits, RoundingDirection::Up)
                            .mul_round(&column_norm, p.bits, RoundingDirection::Up),
                        p.bits,
                        RoundingDirection::Up,
                    );
            }
        }
        Ok(Some(EndpointLinearMap {
            values,
            arithmetic_errors: errors,
        }))
    }

    /// Match a regular boundary in the local Frobenius convergence domain.
    /// `winding` is the branch of log(x) at that point. Boundary root signs
    /// select the algebraic sheet; subsequent evaluation uses the same local
    /// logarithm convention. No global physical prescription is inferred.
    #[allow(clippy::too_many_arguments)]
    pub fn match_boundary(
        &self,
        boundary: &EpsilonBoundary,
        seeds: &BTreeMap<Symbol, RootSeed>,
        p: Precision,
        order: usize,
        winding: i32,
        context: &RunContext,
    ) -> Result<AlgebraicEndpointExpansion> {
        context.cancellation.check()?;
        let (boundary_lift, matching_branches, regular_domain_guards) =
            self.lifted.lift_boundary_data(boundary, seeds, p)?;
        let basis = self
            .prepared
            .evaluate(p, &Default::default(), order, context)?;
        let constants = crate::numeric::solve(
            p,
            basis.evaluate_with_winding(&boundary.point, &Default::default(), winding)?,
            boundary_lift.values,
        )?;
        context.cancellation.check()?;
        Ok(AlgebraicEndpointExpansion {
            basis,
            constants,
            size: self.lifted.size,
            count: self.lifted.count,
            leading: boundary.leading,
            matching_branches,
            variable: self.lifted.source.system.variable,
            regular_domain_guards,
        })
    }
}

impl AlgebraicEndpointExpansion {
    pub fn matching_branches(&self) -> &BranchState {
        &self.matching_branches
    }
    pub fn basis(&self) -> &FrobeniusBasis {
        &self.basis
    }
    pub fn constants(&self) -> &[C] {
        &self.constants
    }

    /// Evaluate a nonzero local coordinate. Fractional powers and logarithms
    /// share the requested winding. The caller must stay inside the local
    /// convergence disk; precision/order refinement is required for evidence.
    pub fn evaluate(&self, point: &C, winding: i32) -> Result<EpsilonBoundary> {
        let rules = BTreeMap::from([(
            Atom::var(self.variable),
            exact_point(self.basis.precision, point)?,
        )]);
        if self
            .regular_domain_guards
            .iter()
            .any(|a| decoded(&substitute(a, &rules)).is_zero())
        {
            return Err(Error::InvalidInput("algebraic endpoint series evaluation lies on a retained singularity; use coefficient_limits at the expansion center".into()));
        }
        let matrix = self
            .basis
            .evaluate_with_winding(point, &Default::default(), winding)?;
        let p = self.basis.precision;
        let values = matrix
            .iter()
            .take(self.size * self.count)
            .map(|row| {
                row.iter()
                    .zip(&self.constants)
                    .fold(p.zero(), |sum, (a, b)| p.add(&sum, &p.mul(a, b)))
            })
            .collect::<Vec<_>>();
        Ok(EpsilonBoundary {
            point: point.clone(),
            leading: self.leading,
            coefficients: values.chunks(self.size).map(<[C]>::to_vec).collect(),
        })
    }

    /// Finite endpoint limits of the retained epsilon coefficients, projecting
    /// only original components. Divergent auxiliary rows are irrelevant.
    /// These limits are taken after epsilon expansion: symbolic dimensional
    /// sectors cannot be selected from this hierarchy. In particular, logarithms
    /// from an x^epsilon sector return a divergence error. No small-mass
    /// substitution or achieved-accuracy certification is performed.
    pub fn coefficient_limits(&self) -> Result<Vec<Vec<C>>> {
        let n = self.basis.columns.len();
        let values = (0..self.size * self.count)
            .map(|component| {
                let weights = (0..n)
                    .map(|j| Atom::num(i64::from(component == j)))
                    .collect::<Vec<_>>();
                crate::frobenius::project_limit(
                    &self.basis,
                    &self.constants,
                    &weights,
                    symbol!("symbolica_amflow::algebraic_endpoint_epsilon"),
                    symbol!("symbolica_amflow::algebraic_endpoint_projection"),
                    &Default::default(),
                )
            })
            .collect::<Result<Vec<_>>>()?;
        Ok(values.chunks(self.size).map(<[C]>::to_vec).collect())
    }
}

fn stored_ball(a: &C, p: Precision) -> ComplexBall {
    let mut ball = ComplexBall::new(RealBall::exact(a.re.clone()), RealBall::exact(a.im.clone()));
    ball.set_precision(p.bits);
    ball
}
fn ball_upper(a: &ComplexBall, p: Precision) -> Float {
    let absolute = |a: &Float| {
        if *a < p.real(0) {
            -a.clone()
        } else {
            a.clone()
        }
    };
    absolute(&a.re.center)
        .add_round(&a.re.radius, p.bits, RoundingDirection::Up)
        .add_round(&absolute(&a.im.center), p.bits, RoundingDirection::Up)
        .add_round(&a.im.radius, p.bits, RoundingDirection::Up)
}

fn conditioned_inverse(
    matching: &Matrix<FloatField<C>>,
    p: Precision,
    context: &RunContext,
) -> Result<(Matrix<FloatField<ComplexBall>>, Float)> {
    context.cancellation.check()?;
    let n = matching.nrows();
    let inverse = matching.inv().map_err(|e| Error::InsufficientPrecision {
        minimum_bits: p.bits.saturating_mul(2),
        context: format!("endpoint matching matrix: {e}"),
    })?;
    context.cancellation.check()?;
    let exact = |a: &C| stored_ball(a, p);
    let ball_field = FloatField::from_rep(exact(&p.zero()));
    let a = matching.map(exact, ball_field.clone());
    let b = inverse.map(exact, ball_field.clone());
    let identity = Matrix::identity(n as u32, ball_field.clone());
    let residual = &identity - &(&a * &b);
    let upper = |a: &ComplexBall| ball_upper(a, p);
    let norm = |a: &Matrix<FloatField<ComplexBall>>| {
        (0..a.nrows())
            .map(|i| {
                (0..a.ncols()).fold(p.real(0), |sum, j| {
                    sum.add_round(
                        &upper(&a[(i as u32, j as u32)]),
                        p.bits,
                        RoundingDirection::Up,
                    )
                })
            })
            .reduce(|a, b| if a > b { a } else { b })
            .unwrap_or_else(|| p.real(0))
    };
    let defect = norm(&residual);
    if !defect.is_finite() || defect >= p.real(1) / p.real(2) {
        return Err(Error::InsufficientPrecision {
            minimum_bits: p.bits.saturating_mul(2),
            context: "endpoint matching inverse has an unresolved residual".into(),
        });
    }
    let inverse_error = norm(&b)
        .mul_round(&defect, p.bits, RoundingDirection::Up)
        .div_round(
            &p.real(1)
                .sub_round(&defect, p.bits, RoundingDirection::Down),
            p.bits,
            RoundingDirection::Up,
        );
    Ok((b, inverse_error))
}
