#![allow(dead_code,unused_imports)]
use symbolica_amflow::*;use symbolica::prelude::*;use std::collections::{BTreeMap,BTreeSet};
#[path="../source/coefficient.rs"]mod coefficient;
#[path="../source/moments.rs"]mod moments;
#[path="../gaussian-wide-source/angular.rs"]mod angular;
#[path="../gaussian-wide-source/compact_exact.rs"]mod compact_exact;
const LIMIT:usize=200000;
fn poly(p:&Atom,vars:&[Atom],cap:usize)->Result<Vec<(Vec<i16>,Atom)>>{let ts=coefficient::exact_coefficient_list(p,vars)?;if ts.len()>cap{return Err(Error::Limit("polynomial terms".into()))}ts.into_iter().map(|(m,c)|{let ps=coefficient::powers(&m,vars)?;if ps.iter().any(|&p|p<0){return Err(Error::InvalidInput("polynomial".into()))}Ok((ps,c))}).collect()}
#[test]fn radial_native_normalization(){let p=Precision::decimal(60).unwrap();let mut checked=0;for d in [Rational::from((11,2)),Rational::from((15,2))]{let pi=ComplexFloat::new(p.real(1).pi(),p.real(0));let conversion=p.div(&p.pow(&p.scale(&pi,2,1),&p.rational(&d)),&p.pow(&pi,&p.rational(&((d.clone()+Rational::one())/Rational::from(2)))));for mu in [Rational::one(),Rational::from(2)]{let a=p.div(&p.pow(&p.rational(&mu),&p.rational(&(d.clone()-Rational::one()))),&p.mul(&p.pow(&pi,&p.rational(&Rational::from((1,2)))),&p.gamma_real(&p.rational(&(d.clone()/Rational::from(2))).re).unwrap()));let shell=finite_density::compact::CompactShell{mass_squared:Rational::zero(),chemical_potential:mu.clone()};for n in 1..=3{for r in 0..=3{for j in 0..=2{let old=shell.dimensionally_continued_massless_raised_moment(&d,n,r,j,p).unwrap();let raw=p.mul(&conversion,&if n%2==0{old}else{p.neg(&old)});let exact=moments::radial(&Atom::num(d.clone()),n as i16,0,0,r as i16,j as i16,&mu).unwrap();let new=p.mul(&a,&p.eval(&exact,&ahash::HashMap::default()).unwrap());assert!(p.close(&raw,&new,45),"n={n} r={r} j={j}");checked+=1}}}}}assert_eq!(checked,144);}
#[test]fn upper_surfaces_are_exact_mu_derivatives(){let d=Atom::num((11,2));let ms=symbol!("moment_test::mu");let m=Atom::var(ms);let mut checked=0;for n in 1..=3{for r in 0..=3{for j in 0..=2{let bulk=moments::radial(&d,n,0,0,r,j,&Rational::one()).unwrap();let beta=&d+Atom::num(r+2*j+1-2*n);let mut derivative=bulk*m.pow(beta);for s in 1..=4{derivative=derivative.derivative(ms);let sign=if (s-1)%2==0{1}else{-1};let fact=(1..s).fold(1i64,|a,b|a*i64::from(b));let normalized=&derivative/m.pow(&d-Atom::one())*Atom::num((sign,fact));let normalized=family::substitute(&normalized,&BTreeMap::from([(m.clone(),Atom::num(2))])).together().cancel();let direct=moments::radial(&d,n,s,0,r,j,&Rational::from(2)).unwrap();assert!((normalized-direct).together().cancel().is_zero());checked+=1}}}}assert_eq!(checked,144);}
#[test]fn compact_graph_moments_match_native_tensor_projection(){let eps=symbol!("moment_test::epsilon");let mut checked=0;for k in [2usize,3]{let pairs=(0..k).flat_map(|i|(i..k).map(move|j|(i,j))).collect::<Vec<_>>();let coords=(0..pairs.len()+k).map(|i|Atom::var(symbol!(format!("moment_test::x{i}")))).collect::<Vec<_>>();let space=integrand::RegionFactorSpace{coordinates:coords.clone(),source_coordinate_indices:(0..coords.len()).collect(),source_loop_indices:(0..k).collect(),template:IntegralFamily{name:"compact-test".into(),loops:(0..k).map(|i|format!("q{i}")).collect(),external:vec!["U".into()],external_gram:vec![vec![Atom::one()]],propagators:vec![],physical_propagators:0,dimension:4,epsilon:eps}};for n in [1i16,2]{for upper in [0i16,1,2]{let ds=(0..k).map(|i|finite_density::boundary::OccupiedBoundaryDistribution{source_loop_index:i,shell:finite_density::compact::CompactShell{mass_squared:Rational::zero(),chemical_potential:Rational::one()},cut_index:if i==0{n}else{1},upper_index:if i==0{upper}else{0},lower_index:0}).collect::<Vec<_>>();let mut cm=compact_exact::CompactMoments::new(k,Atom::num((11,2)),ds.iter().map(|x|(x.cut_index,x.upper_index,x.lower_index,x.shell.chemical_potential.clone())).collect(),LIMIT).unwrap();for degree in 0..=4{let mut polynomial=Atom::one();for(j,&(a,b))in pairs.iter().enumerate(){if a!=b{polynomial*=coords[j].pow(degree)}}polynomial*=&coords[pairs.len()].pow(2);let expected=moments::integrate(&polynomial,&space,&ds).unwrap();let expected=family::substitute(&expected,&BTreeMap::from([(Atom::var(eps),Atom::num((-5,4)))])).together().cancel();let actual=cm.integrate(&polynomial,&coords).unwrap();assert!((expected-actual).together().cancel().is_zero(),"k={k} n={n} upper={upper} degree={degree}");checked+=1;}}}}assert_eq!(checked,60);}
