import json,pathlib,hashlib,collections
r=pathlib.Path(__file__).resolve().parent;h=lambda p:hashlib.sha256(p.read_bytes()).hexdigest();sectors=[]
for mode in ['single3','double']:
 v=json.loads((r/mode/'profile/result.json').read_text());res=json.loads((r/mode/'resources.json').read_text());binding=json.loads((r/mode/'run-binding.json').read_text());ticks=binding['clock_ticks_per_second'];by={t['phase']:t for t in v['timings']};assert res['exit_code']==0 and binding['inputs_unchanged'] and v['empty_union_preserves_exact_encoded_bytes']
 def phase(name):
  q=by[name];return {'wall_seconds':q['wall_seconds'],'user_cpu_seconds':q['user_cpu_ticks']/ticks,'system_cpu_seconds':q['system_cpu_ticks']/ticks}
 sums={k:sum(t['wall_seconds']for t in v['timings']if t['phase'].endswith(k))for k in ['apply-native','reduce-native','apply-expression-json','reduce-expression-json']}
 status=dict(collections.Counter(x['application']['status']for x in v['points']));reasons=dict(collections.Counter(u['reason']for p in v['points']for u in p['reduction']['unresolved']))
 sectors.append({'sector':mode,'rules':v['rule_count'],'sources':v['source_count'],'program_bytes':v['program_bytes'],'point_count':len(v['points']),'source_loading_wall_seconds':sum(by[n]['wall_seconds']for n in ['read_program_bytes','inspect_envelope','decode_program_record','import_symbolica_and_coefficient_table','construct_exact_source_context']),'decode_and_full_replay':phase('decode_generated_and_replay_all_rules'),'empty_same_source_union':phase('union_replayed_with_empty_same_source'),'encoding_before':phase('encode_before_empty_union'),'encoding_after':phase('encode_after_empty_union'),'point_phase_wall_totals':sums,'application_statuses':status,'successful_reduction_rule_applications':sum(x['reduction']['rule_applications']for x in v['points']),'unresolved_reasons':reasons,'conditions_retained':True,'work_limits':v['limits'],'empty_union_encoded_bytes_unchanged':True,'resources':{'path':f'{mode}/resources.json','sha256':h(r/mode/'resources.json'),'wall_seconds':res['wall_seconds'],'peak_child_rss_kib':res['peak_child_rss_kib']}})
out={'scope':'Read-only unchanged-native profile; no discovery, new reducer, mathematical assumptions or production changes. Each selected checkpoint is copied and source/binary hash-bound. Full proof replay and empty same-source replayed union independently checked.','sectors':sectors,'conclusion':'Repeated proof replay dominates this immutable-program experiment. Empty same-source union costs nearly as much as initial proof decoding/replay while leaving exact encoded bytes unchanged. This directly motivates reviewing a separate invariant-preserving composition of already-verified immutable programs.','limitations':['All32 selected current requested/frontier labels are NoApplicableRule, with zero successful recursive rule applications. Native point timings therefore measure full-corpus uncovered-rule scans, not deep reductions or nontrivial coefficient substitutions.','Expression timings include only simple unresolved outputs, mostly unit coefficients and no applied guards; they cannot bound expensive symbolic-expression conversion in other targets.','Rule scanning and native polynomial substitution were not independently instrumented. No claim identifies which dominates a nontrivial applicable reduction.','One sequential observation per checkpoint on a shared host; CPU ticks support replay CPU cost, but no cross-run performance superiority is claimed.'],'limits':{'labels_per_checkpoint':16,'max_rule_applications_per_label':4096,'max_pending_integrals_per_label':4096,'timeout_seconds_per_checkpoint':600},'implementation_reading':'implementation-reading.json'}
(r/'summary.json').write_text(json.dumps(out,indent=2)+'\n')
(r/'README.md').write_text('Repeated native proof replay dominates this read-only profile. For the13,850-rule single-cut checkpoint, decode plus replay took91.606 seconds and union with an empty same-source program took91.160 seconds. For the3,114-rule double-cut checkpoint, the corresponding times were34.765 and34.065 seconds. The empty unions preserve the exact encoded program bytes. Their cost comes from replaying unchanged already-validated rules, not additional discovery.\n\nSource byte/record/coefficient/context loading took under a second in either case. Proof encoding took0.85–0.88 seconds for the larger program and0.26 seconds for the smaller. The measured phases include Linux CPU ticks; the first program spent90.75 and90.50 user CPU seconds in decode/replay and empty union, respectively. This was CPU work rather than primarily a host scheduling delay.\n\nEach checkpoint used8 lexicographic current requested labels and8 distinct frontier labels. All32 turned out to be NoApplicableRule, so recursive reduction performed no successful applications. Their full-corpus scans took roughly0.2–2 milliseconds each; formatting the simple unresolved results was smaller apart from first-use initialization. These timings do not profile deep reductions, nontrivial coefficient specialization, or large expressions. The experiment does not isolate native rule scanning from polynomial substitution and makes no claim about their relative cost on covered targets. All exact statuses, coefficients and conditions remain in the outputs.\n\nThe native programs were decoded under exact original source bindings. The consuming old-first empty union retained source context, rule order and empty stopping set, and byte-identical re-encoding was asserted. No source, rule or admission change occurred. Each run had a600-second timeout and reduction limits4096 applications/4096 pending labels. Both exited0. Measurements were sequential on a shared host, and are not an exclusive-machine benchmark.\n\nThis evidence justifies reviewing a separate invariant-preserving composition API for immutable programs already verified under the same context. It does not justify weakening persisted-program decoding or accepting unverified rules. See summary.json for exact timings and limits, per-sector profile/result.json for full output, and build/input/run bindings for reproducibility.\n')
files=[p for p in sorted(r.rglob('*'))if p.is_file()and p.name!='manifest.json'];(r/'manifest.json').write_text(json.dumps({'schema':'sha256-file-manifest-v1','files':[{'path':str(p.relative_to(r)),'bytes':p.stat().st_size,'sha256':h(p)}for p in files]},indent=2)+'\n');print('files',len(files),'manifest',h(r/'manifest.json'));print(json.dumps(sectors,indent=2))
