import json,pathlib,hashlib,re
r=pathlib.Path(__file__).resolve().parent;old=r.parent/'2026-10-10-singleton-energy-ward-native-controls';h=lambda p:hashlib.sha256(p.read_bytes()).hexdigest()
a=json.loads((r/'original/result.json').read_text());b=json.loads((r/'ward-first/result.json').read_text());previous=json.loads((old/'original/result.json').read_text());rows=[]
for i,(p,q)in enumerate(zip(a['probes'],b['probes'])):
 x,y=p['application'],q['application'];idx=int(re.search(r'rule: (\d+)',y['status'])[1]);actual=q['proof_sources'][idx];point=p['selection']['point'];leading=point[0]==1 and point[6]<=-2 and point[7]==point[8]==point[10]==0 and point[9]>=1
 assert p['roundtrip']and q['roundtrip'];assert a['selection_observations'][i]['status']=='Unresolved(NoApplicableRule)';assert b['selection_observations'][i]['status']=='Unresolved(NoApplicableRule)'
 if i<16:assert p['application']==previous['probes'][i]['application']
 row={'ordinal':i,'selection':p['selection'],'new_leading_domain':leading,'baseline_rhs_terms':len(x['rhs']),'ward_first_rhs_terms':len(y['rhs']),'exact_rhs_equal':x['rhs']==y['rhs'],'ordered_conditions_equal':x['conditions']==y['conditions'],'statuses':[x['status'],y['status']],'point_fallback':[p['point_fallback'],q['point_fallback']],'selected_rule_uses_added_sources':any(z['source_id'].startswith('extended-polynomial-singleton-energy-Ward-v1/')for z in actual),'selected_rule_source_ids':[z['source_id']for z in actual],'baseline_conditions':x['conditions'],'ward_first_conditions':y['conditions']}
 if x['rhs']!=y['rhs']or x['conditions']!=y['conditions']:row['baseline_application']=x;row['ward_first_application']=y
 rows.append(row)
old_manifest=json.loads((old/'manifest.json').read_text());assert all(h(old/f['path'])==f['sha256']for f in old_manifest['files'])
resources=[]
for arm in ['original','ward-first']:
 p=r/f'{arm}-resources.json';v=json.loads(p.read_text());assert v['exit_code']==0;resources.append({'arm':arm,'path':str(p.relative_to(r)),'sha256':h(p),'wall_seconds':v['wall_seconds'],'peak_child_rss_kib':v['peak_child_rss_kib']})
out={'scope':'Source order only: original62 versus two reviewed extended polynomial-energy C1 Ward rows followed by the exact original62. Historical rules only replay selection, never enter discovery. No production edits, reciprocal admission, zero-domain change, numerical periods or closure claim.','sources':[a['source_count'],b['source_count']],'budgets':{'depth':3,'ray_domains_per_label':1,'point_domains_per_label':1,'timeout_seconds_per_arm':300},'selection':json.loads((r/'selection.json').read_text()),'rows':rows,'resources':resources,'rhs_terms':[sum(x['baseline_rhs_terms']for x in rows),sum(x['ward_first_rhs_terms']for x in rows)],'exact_zero_outputs':[sum(x['baseline_rhs_terms']==0 for x in rows),sum(x['ward_first_rhs_terms']==0 for x in rows)],'changed_rhs':sum(not x['exact_rhs_equal']for x in rows),'changed_ordered_conditions':sum(not x['ordered_conditions_equal']for x in rows),'selected_rules_using_new_sources':sum(x['selected_rule_uses_added_sources']for x in rows),'new_leading_rows_unchanged':all(x['exact_rhs_equal']and x['ordered_conditions_equal']for x in rows if x['new_leading_domain']),'native_roundtrips':40,'all_rhs_admitted':a['all_rhs_labels_admitted']and b['all_rhs_labels_admitted'],'original16_baseline_reproduced':True,'previous_manifest_verified_unchanged':{'path':str(old/'manifest.json'),'sha256':h(old/'manifest.json'),'files':len(old_manifest['files'])},'condition_analysis':{'ordinal0':'Every old/new condition is a nonzero rational multiple of 2*epsilon-3 or its square: 9-12*epsilon+4*epsilon^2=(2*epsilon-3)^2. Both therefore require precisely 2*epsilon-3 !=0. All raw conditions are retained in rows/results.','ordinal1':'All old/new conditions are nonzero rational multiples of eta. Both require eta!=0. All raw conditions retained.'},'conclusion':'Putting the extra identities first makes them enter14 selected native proofs, but only two bulk E-degree1 outputs change (3→3 and4→3 terms). All seven new-leading H1/E-degree2 points are unchanged. Coverage and exact-zero counts do not improve. This small presentation effect does not justify promotion or a full pilot.','performance_scope':'Shared host; timing includes historical-program selection replay. No speed comparison.'}
(r/'summary.json').write_text(json.dumps(out,indent=2)+'\n')
(r/'README.md').write_text('Putting the two extended polynomial-energy Ward rows before the original62 makes them enter14 of20 selected native proofs. It changes only two bulk E-degree1 reductions: one stays at3 terms with different coefficients, and one contracts4→3. Total RHS terms change29→28. All20 labels remain applicable and both arms produce10 exact-zero outputs. All40 encoded native programs decode/replay and keep admitted RHS labels.\n\nThe original16-label sample contained three own-C1/Hupper1/E-degree2 points in the newly available leading domain. The saved frontier has19 such points and none at higher upper index or higher energy degree. Four additional points were selected lexicographically, giving seven new-leading points in the20-label sample. All seven keep exactly identical RHS and ordered conditions under Ward-first ordering. The four out-of-source-guard controls also remain unchanged.\n\nBoth changed outputs retain the same exceptional parameter loci: the first requires2*epsilon−3 nonzero (the old conditions include its square and rational multiples), and the second requires eta nonzero. No condition was erased from either saved native result. These are independently replayed source-derived recurrences, not a comparison of evaluated periods.\n\nBoth arms use exactly the same source/input geometry, zero domains and admitted indices as the previous appended-row control, with depth3, anchored-ray cap1, exact-point fallback cap1 and a300-second timeout. All20 cases need point fallback. The previous original16 outputs are reproduced exactly and its complete56-file manifest is verified unchanged. The only new-arm change is source order: new2 then original62. Existing proof rules are discarded after their independent selection-status audit.\n\nThe small source-order effect establishes that the new rows can participate, but gives no coverage or zero-output improvement and does not justify production promotion or a full pilot. No reciprocal-energy domain or production code changed. See summary.json for exact changed recurrences, all retained conditions and selected proof provenance. Native proof binaries remain raw; build/input/resource bindings are preserved. Shared-host timings are not a performance claim.\n')
files=[p for p in sorted(r.rglob('*'))if p.is_file()and p.name!='manifest.json'];(r/'manifest.json').write_text(json.dumps({'schema':'sha256-file-manifest-v1','files':[{'path':str(p.relative_to(r)),'bytes':p.stat().st_size,'sha256':h(p)}for p in files]},indent=2)+'\n');print('files',len(files),'manifest',h(r/'manifest.json'))
