#![allow(dead_code,unused_imports)]
use symbolica_amflow::*;use symbolica::prelude::*;use std::collections::{BTreeMap,BTreeSet};
#[path="../source/algebra.rs"]mod algebra;#[path="../source/coefficient.rs"]mod coefficient;#[path="../source/moments.rs"]mod moments;
mod angular;
mod compact_exact;
use feynkit_graph::IntegralFamily as NativeFamily;use feynkit_kinematics::Kinematics;
use reduction::ReductionBackend;
const LIMIT:usize=200000;
fn err(e:impl std::fmt::Display)->Error{Error::Unsupported(e.to_string())}
fn s(a:&Atom)->String{a.to_canonical_string()}
fn poly(p:&Atom,vars:&[Atom],cap:usize)->Result<Vec<(Vec<i16>,Atom)>>{let ts=coefficient::exact_coefficient_list(p,vars)?;if ts.len()>cap{return Err(Error::Limit("polynomial terms".into()))}ts.into_iter().map(|(m,c)|{let ps=coefficient::powers(&m,vars)?;if ps.iter().any(|&p|p<0)||vars.iter().any(|a|{let AtomView::Var(v)=a.as_view()else{return true};!c.derivative(v.get_symbol()).is_zero()}){return Err(err("not polynomial in declared coordinates"))}Ok((ps,c))}).collect()}
fn monomial(vars:&[Atom],ps:&[i16])->Atom{vars.iter().zip(ps).fold(Atom::one(),|a,(v,&p)|a*v.pow(i64::from(p)))}
fn factorial(n:i64)->Atom{(1..=n).fold(Atom::one(),|a,n|a*Atom::num(n))}
fn truncate(p:&Atom,diag:&[Atom],cuts:&[i16])->Result<Atom>{let mut out=Atom::zero();for(ps,c)in poly(p,diag,LIMIT)?{if ps.iter().zip(cuts).all(|(&p,&n)|p<n){out+=c*monomial(diag,&ps)}}Ok(out.expand())}
fn fkey(f:&IntegralFamily)->String{serde_json::json!({"loops":f.loops.len(),"external":f.external,"physical":f.physical_propagators,"D":"13/2","propagators":f.propagators.iter().map(|p|serde_json::json!({"constant":s(&p.constant),"coefficients":p.scalar_products.iter().map(s).collect::<Vec<_>>()})).collect::<Vec<_>>()}).to_string()}
struct Hard{backend:RustRedBackend,eps:Rational,context:RunContext,cache:BTreeMap<(String,Vec<i16>),Vec<(String,Atom)>>,conditions:BTreeSet<String>,records:Vec<serde_json::Value>}
impl Hard{
 fn reduce(&mut self,p:&Atom,vars:&[Atom],f:&IntegralFamily)->Result<Vec<(String,Atom)>>{let mut out=BTreeMap::new();for t in integrand::to_integrals(p,vars,f,LIMIT)?{let key=(fkey(&t.family),t.integral.0.clone());if !self.cache.contains_key(&key){let r=self.backend.reduce_at_epsilon(&t.family,std::slice::from_ref(&t.integral),&self.eps,&self.context)?;for c in &r.nonzero_conditions{if c.is_zero(){return Err(err("native hard condition vanished"))}self.conditions.insert(s(c));}let m=if let Some(m)=r.rules.get(&t.integral){m.clone()}else if r.residuals.contains(&t.integral){BTreeMap::from([(t.integral.clone(),Atom::one())])}else{return Err(err("native hard result omits target reconstruction"))};let v=m.iter().map(|(i,c)|(serde_json::json!({"family":key.0,"master":i.0}).to_string(),c.clone())).collect::<Vec<_>>();self.records.push(serde_json::json!({"family":key.0,"input":t.integral.0,"terms":v.iter().map(|(m,c)|serde_json::json!({"master":m,"coefficient":s(c)})).collect::<Vec<_>>(),"conditions":r.nonzero_conditions.iter().map(s).collect::<Vec<_>>()}));self.cache.insert(key.clone(),v);}for(m,c)in &self.cache[&key]{*out.entry(m.clone()).or_insert_with(Atom::zero)+=&t.coefficient*c;}}
 Ok(out.into_iter().map(|(m,c)|(m,c.together().cancel())).collect())}
}
fn main()->Result<()>{
 let args=std::env::args().collect::<Vec<_>>();let output=std::path::PathBuf::from(&args[2]);std::fs::create_dir_all(&output).unwrap();let count:usize=args[3].parse().unwrap();if count==0||count>64{return Err(Error::Limit("coefficient count1..64".into()))}
 let input:finite_density::DensityInput=serde_json::from_slice(&std::fs::read(&args[1]).unwrap()).unwrap();let prepared=input.prepare()?;let f=prepared.occupied_cut(&[0,3],4096)?.at_physical_masses();let k=f.shells().len();let h=f.loops()-k;let eps=symbol!("integrated_moment::epsilon");let eta=Atom::var(symbol!("integrated_moment::eta"));let d=Atom::num((13,2));
 let shifted=(0..f.physical_slots()).filter(|&i|f.roles()[i]==rustred::solver::guarded::IndexRole::Ordinary).collect::<Vec<_>>();let evidence=finite_density::massless_endpoint::MasslessFlowEvidence::new(&prepared,&f,&shifted,Default::default())?;evidence.validate_labels(&f,&f.targets().iter().flat_map(|t|t.keys().cloned()).collect::<Vec<_>>())?;
 if prepared.physical_masses().iter().any(|a|!a.is_zero())||f.routing_determinant()!=&Rational::one(){return Err(err("initial Gaussian owner requires zero physical masses and unit routing determinant"))}
 let routing=algebra::matmul(&input.edges.iter().map(|e|e.routing.iter().map(|x|Atom::parse(x,"rustflow_density",Default::default()).map_err(err)).collect::<Result<Vec<_>>>()).collect::<Result<Vec<_>>>()?,f.inverse_routing());
 let pairs=(0..f.loops()).flat_map(|i|(i..f.loops()).map(move|j|(i,j))).collect::<Vec<_>>();let gram=|i:usize,j:usize|f.coordinates()[pairs.iter().position(|&p|p==(i.min(j),i.max(j))).unwrap()].clone();let eoff=pairs.len();
 let compact_pairs=(0..k).flat_map(|i|(i..k).map(move|j|(i,j))).collect::<Vec<_>>();let compact_coords=compact_pairs.iter().map(|&(i,j)|gram(i,j)).chain((0..k).map(|i|f.coordinates()[eoff+i].clone())).collect::<Vec<_>>();let diag=(0..k).map(|i|gram(i,i)).collect::<Vec<_>>();
 let loopatoms=(0..h).map(|i|Atom::var(symbol!(format!("integrated_moment_gauss::k{i}")))).collect::<Vec<_>>();let exatoms=(0..k).map(|i|Atom::var(symbol!(format!("integrated_moment_gauss::q{i}")))).collect::<Vec<_>>();
 let mut kin=Kinematics::new().with_momenta(loopatoms.iter().chain(&exatoms).cloned()).map_err(err)?;for i in 0..k{kin=kin.with_mass_squared(&exatoms[i],gram(i,i)).map_err(err)?;for j in i+1..k{kin=kin.with_scalar_product(&exatoms[i],&exatoms[j],gram(i,j)).map_err(err)?;}}
 let virtual_coordinates=pairs.iter().enumerate().filter(|(_,(_,b))|*b>=k).map(|(i,_)|f.coordinates()[i].clone()).chain((k..f.loops()).map(|i|f.coordinates()[eoff+i].clone())).collect::<Vec<_>>();
 let mut hard=Hard{backend:RustRedBackend{bubble_subloops:false,..Default::default()},eps:Rational::from((-5,4)),context:RunContext::default(),cache:BTreeMap::new(),conditions:BTreeSet::new(),records:Vec::new()};let mut totals=BTreeMap::<(usize,usize,String),Atom>::new();let mut audits=Vec::new();
 for(ti,target)in f.targets().iter().enumerate(){for(label,weight)in target{
  let active=shifted.iter().copied().filter(|&s|label.0[s]>0&&routing[s][k..].iter().any(|v|!v.is_zero())).collect::<Vec<_>>();let pure=shifted.iter().copied().filter(|&s|label.0[s]>0&&routing[s][k..].iter().all(|v|v.is_zero())).collect::<Vec<_>>();if active.is_empty(){return Err(err("Gaussian virtual support empty: needs ordinary zero owner"))}
  let alpha=(0..active.len()).map(|i|Atom::var(symbol!(format!("integrated_moment_gauss::alpha{i}")))).collect::<Vec<_>>();let allmom=exatoms.iter().chain(&loopatoms).cloned().collect::<Vec<_>>();let den=active.iter().map(|&s|{let q=routing[s].iter().zip(&allmom).fold(Atom::zero(),|a,(c,q)|a+c*q);Ok(kin.scalar_product(&q,&q).map_err(err)?-&eta)}).collect::<Result<Vec<_>>>()?;
  let native=NativeFamily::new(loopatoms.clone(),exatoms.clone(),den,&kin).map_err(err)?;let(u,full_f)=native.symanzik(&alpha).map_err(err)?;let sum=alpha.iter().cloned().sum::<Atom>();let v=(&full_f-&eta*&u*&sum).expand();
  let a=(0..h).map(|i|(0..h).map(|j|active.iter().zip(&alpha).fold(Atom::zero(),|s,(&e,x)|s+x*&routing[e][k+i]*&routing[e][k+j])).collect::<Vec<_>>()).collect::<Vec<_>>();if !(algebra::determinant(a.clone())-&u).expand().is_zero(){return Err(err("HEPKit U replay"))}let inv=algebra::inverse(&a)?;let b=(0..h).map(|i|(0..k).map(|j|active.iter().zip(&alpha).fold(Atom::zero(),|s,(&e,x)|s+x*&routing[e][k+i]*&routing[e][j])).collect::<Vec<_>>()).collect::<Vec<_>>();let means=(0..h).map(|i|(0..k).map(|j|-(0..h).fold(Atom::zero(),|s,l|s+&inv[i][l]*&b[l][j])).collect::<Vec<_>>()).collect::<Vec<_>>();
  let c=active.iter().zip(&alpha).fold(Atom::zero(),|s,(&e,x)|s+x*(0..k).flat_map(|i|(0..k).map(move|j|(i,j))).fold(Atom::zero(),|s,(i,j)|s+&routing[e][i]*&routing[e][j]*gram(i,j)));let schur=(0..h).flat_map(|i|(0..h).map(move|j|(i,j))).fold(Atom::zero(),|s,(i,j)|s+(0..k).flat_map(|a|(0..k).map(move|b|(a,b))).fold(Atom::zero(),|s,(l,m)|s+&b[i][l]*&inv[i][j]*&b[j][m]*gram(l,m)));if !(&v+&u*(c-schur)).together().cancel().is_zero(){return Err(err("full off-shell F Gaussian replay"))}
  let mut numerator=Atom::one();for s in 0..f.input_slots(){if label.0[s]<0{numerator*=f.factors()[s].pow(-i64::from(label.0[s]));}}
  let mut mean_map=BTreeMap::new();for i in 0..h{for j in 0..k{mean_map.insert(gram(k+i,j),(0..k).fold(Atom::zero(),|s,l|s+&means[i][l]*gram(l,j)));}mean_map.insert(f.coordinates()[eoff+k+i].clone(),(0..k).fold(Atom::zero(),|s,l|s+&means[i][l]*&f.coordinates()[eoff+l]));}
  let mut groups=BTreeMap::<usize,Atom>::new();for(ps,c)in poly(&numerator,&virtual_coordinates,LIMIT)?{let mut degree=0i64;for(x,&n)in virtual_coordinates.iter().zip(&ps){let two=pairs.iter().enumerate().any(|(z,&(i,j))|i>=k&&j>=k&&f.coordinates()[z]==*x);degree+=i64::from(n)*if two{2}else{1};}if degree>1{return Err(err("Gaussian prototype supports original virtual numerator degree<=1"))}let p=degree as usize;let centered=family::substitute(&monomial(&virtual_coordinates,&ps),&mean_map);*groups.entry(p).or_default()+=(c*centered*&u.clone().pow(p as i64)).together().cancel();}
  let cuts=f.shells().iter().map(|s|label.0[s.physical_slot]).collect::<Vec<_>>();let ds=f.shells().iter().map(|s|(label.0[s.physical_slot],label.0[s.upper_slot],label.0[s.lower_slot],s.chemical_potential.clone())).collect::<Vec<_>>();let mut cm=compact_exact::CompactMoments::new(k,&d-Atom::one(),ds,LIMIT)?;
  let mut pure_series=vec![Atom::zero();count];pure_series[0]=Atom::one();let mut p0=0i64;for &slot in &pure{let power=i64::from(label.0[slot]);p0+=power;let mut factor=vec![Atom::one();count];for j in 1..count{factor[j]=truncate(&(&factor[j-1]*&f.factors()[slot]*Atom::num(power+j as i64-1)/Atom::num(j as i64)),&diag,&cuts)?;}let old=pure_series.clone();for n in 0..count{pure_series[n]=truncate(&(0..=n).fold(Atom::zero(),|s,j|s+&old[j]*&factor[n-j]),&diag,&cuts)?;}if power%2!=0{for c in &mut pure_series{*c=-c.clone()}}}
  let virtual_p=active.iter().map(|&s|i64::from(label.0[s])).sum::<i64>();let hardpairs=(0..h).flat_map(|i|(i..h).map(move|j|(i,j))).collect::<Vec<_>>();let hardvars=(0..hardpairs.len()).map(|i|Atom::var(symbol!(format!("integrated_moment_gauss::G{i}")))).collect::<Vec<_>>();let hg=|i:usize,j:usize|hardvars[hardpairs.iter().position(|&p|p==(i.min(j),i.max(j))).unwrap()].clone();let determinant=algebra::determinant((0..h).map(|i|(0..h).map(|j|hg(i,j)).collect()).collect());let vacuum_den=active.iter().map(|&s|hardpairs.iter().fold(Atom::num(-1),|a,&(i,j)|a+&routing[s][k+i]*&routing[s][k+j]*Atom::num(if i==j{1}else{2})*hg(i,j))).collect::<Vec<_>>();let template=IntegralFamily{name:"generic_gaussian_vacuum_coefficient".into(),loops:(0..h).map(|i|format!("K{i}")).collect(),external:vec![],external_gram:vec![],propagators:vec![],physical_propagators:0,epsilon:eps,dimension:4};
  for(p,num)in groups{let mut power=truncate(&num,&diag,&cuts)?;for n in 0..count{
   if n%4==0{eprintln!("target={ti} numerator_group={p} order={n}/{count} hard_labels={}",hard.cache.len());}
   let shift=n+p;let mut bridge=Atom::one();for r in 0..shift{bridge*=Atom::num(-2).pow(h as i64);for j in 0..h{bridge/=&d+Atom::num(2*r as i64-j as i64)}}
   for(ps,compact_poly)in poly(&power,&alpha,LIMIT)?{let mut multiplier=bridge.clone()/factorial(n as i64);let mut expr=determinant.pow(shift as i64);let mut sum_m=0i64;for(i,(&slot,&m))in active.iter().zip(&ps).enumerate(){let base=i64::from(label.0[slot]);sum_m+=i64::from(m);multiplier*=factorial(base+i64::from(m)-1)/factorial(base-1);expr*=vacuum_den[i].pow(-base-i64::from(m));}if (n as i64-sum_m).rem_euclid(2)!=0{multiplier=-multiplier}
    let reduced=hard.reduce(&expr,&hardvars,&template)?;for j in 0..count-n{let value=cm.integrate(&(&compact_poly*&pure_series[j]).expand(),&compact_coords)?;if value.is_zero(){continue}for(channel,c)in &reduced{*totals.entry((ti,n+j,channel.clone())).or_default()+=weight*&multiplier*c*&value;}}
   }
   power=truncate(&(power*&v),&diag,&cuts)?;
  }}
  audits.push(serde_json::json!({"target":ti,"indices":label.0,"active_virtual_slots":active,"pure_compact_slots":pure,"U":s(&u),"F":s(&full_f),"V":s(&v),"gaussian_means":means.iter().map(|r|r.iter().map(s).collect::<Vec<_>>()).collect::<Vec<_>>(),"full_off_shell_replay":true,"gram_determinant":s(&determinant),"eta_leading_exponent_at_D":s(&(Atom::num(h as i64)*&d/Atom::num(2)-Atom::num(virtual_p+p0))),"moment_cache_monomials":cm.evaluated}));
 }}
 let coefficients=totals.into_iter().map(|((target,n,master),c)|serde_json::json!({"target":target,"n":n,"master":master,"coefficient":s(&c.together().cancel())})).collect::<Vec<_>>();let result=serde_json::json!({"schema":"integrated-gaussian-rational-prefix.v1","scope":"Generic Gaussian rank<=1 numerator/ordinary vacuum moment coefficient prototype; no weighted closure/reference inputs","input_identity":prepared.identity(),"dimension":"13/2","q":1,"variable":"z=1/eta","known_prefix_length":count,"tail":"unknown","compact_normalization":"prod_i mu_i^(D-2)/(sqrt(pi)*Gamma((D-1)/2))","audit":audits,"coefficients":coefficients,"hard_reductions":hard.records,"conditions":hard.conditions,"native_backend":hard.backend.identity(),"source_origin":evidence.source_identity(),"convergent_germ_proved":false});let bytes=serde_json::to_vec_pretty(&result).unwrap();if bytes.len()>128*1024*1024{return Err(Error::Limit("retained report128MiB".into()))}std::fs::write(output.join("coefficients.json"),bytes).unwrap();println!("count={count} terms={} native_hard_labels={}",result["coefficients"].as_array().unwrap().len(),hard.cache.len());Ok(())
}
