//! Exact family-matched consumer of an already sealed native ordinary artifact.
//! No recurrence coefficient or period is authored by this adapter.
use super::*;
use rustred::foundry::artifact::ClosedArtifact;
use rustred::reduction::{Reducer,ReductionLimits};
pub struct WideHard<'a>{artifact:&'a ClosedArtifact,reducer:Reducer<'a>,dimension:Atom,map:BTreeMap<Atom,Atom>}
impl<'a> WideHard<'a>{
 pub fn new(artifact:&'a ClosedArtifact)->Result<Self>{
  let ctx=artifact.coefficient_context();if ctx.parameter_names()!=["d"]||artifact.family().external_count()!=0||artifact.family().power_shifts().iter().any(|x|!x.is_zero()){return Err(err("wide artifact requires exact one-parameter unshifted vacuum field"))}
  let dimension=ctx.parameter("d").ok_or_else(||err("artifact dimension missing"))?.to_expression();if artifact.family().dimension().to_expression()!=dimension{return Err(err("artifact dimension identity"))}
  let AtomView::Var(ds)=dimension.as_view()else{return Err(err("dimension must be exact native symbol"))};
  // Native application checks index guards. To specialize d after reduction,
  // this initial adapter additionally requires every guard to be d-independent.
  for rule in artifact.rules(){for g in rule.nonzero_guards(){if !g.polynomial().to_expression().derivative(ds.get_symbol()).is_zero(){return Err(err("parameter-dependent artifact guard requires specialization owner"))}}}
  if !artifact.rule_cells().is_empty()||!artifact.dependencies().is_empty(){return Err(err("wide adapter dependency/cell specialization not implemented"))}
  let reducer=Reducer::with_limits(artifact,ReductionLimits{max_cached_integrals:4096,max_cached_coefficient_terms:LIMIT,max_cached_coefficient_bytes:128*1024*1024,max_rule_applications:100000,..Default::default()}).map_err(err)?;
  Ok(Self{artifact,reducer,map:BTreeMap::from([(dimension.clone(),Atom::num((13,2)))]),dimension})
 }
 pub fn matches(&self,f:&IntegralFamily)->Result<bool>{let a=self.artifact.family();if f.loops.len()!=a.loop_count()||!f.external.is_empty()||!f.external_gram.is_empty()||f.physical_propagators!=a.denominator_count()||f.propagators.len()!=a.denominator_count(){return Ok(false)}for(x,y)in f.propagators.iter().zip(a.denominators()){if x.scalar_products.len()!=y.coefficients().len()||!(&x.constant-y.constant().to_expression()).expand().is_zero(){return Ok(false)}for(u,v)in x.scalar_products.iter().zip(y.coefficients()){if (u-v.to_expression()).expand()!=Atom::zero(){return Ok(false)}}}Ok(true)}
 pub fn reduce(&mut self,f:&IntegralFamily,target:&Integral)->Result<(Vec<(String,Atom)>,serde_json::Value)>{if !self.matches(f)?{return Err(err("wide artifact family mismatch"))}let key=rustred::family::IntegralKey::try_new(target.0.iter().map(|&n|i64::from(n))).map_err(err)?;let result=self.reducer.reduce_unit_mass(&key).map_err(err)?;if result.family_fingerprint()!=self.artifact.family_fingerprint(){return Err(err("wide decomposition family mismatch"))}let mut terms=Vec::new();let mut conditions=Vec::new();for(m,c)in result.terms(){let raw=c.denominator.to_expression();let at=family::substitute(&raw,&self.map).together().cancel();if at.is_zero(){return Err(err("wide native coefficient pole at chosen dimension"))}conditions.push(s(&raw));let value=family::substitute(&c.to_expression(),&self.map).together().cancel();let checked: Rational=Rational::try_from(value.as_view()).map_err(err)?;let channel=serde_json::json!({"family":fkey(f),"master":m.powers()}).to_string();terms.push((channel,Atom::num(checked)));}let record=serde_json::json!({"backend":"sealed native ordinary artifact","algorithm":self.artifact.algorithm_id(),"family_fingerprint":self.artifact.family_fingerprint(),"input":target.0,"terms":terms.iter().map(|(m,c)|serde_json::json!({"master":m,"coefficient":s(c)})).collect::<Vec<_>>(),"raw_coefficient_denominators":conditions,"parameter_independent_rule_guards":self.artifact.rules().iter().flat_map(|r|r.nonzero_guards().iter().map(|g|s(&g.polynomial().to_expression()))).collect::<Vec<_>>()});Ok((terms,record))}
 pub fn report(&self)->serde_json::Value{let st=self.reducer.statistics();serde_json::json!({"algorithm":self.artifact.algorithm_id(),"family_fingerprint":self.artifact.family_fingerprint(),"context_fingerprint":self.artifact.context_fingerprint(),"source_relations":self.artifact.source_relations().len(),"rules":self.artifact.rules().len(),"dimension_symbol":s(&self.dimension),"specialized_dimension":"13/2","rule_applications":st.rule_applications(),"cached_integrals":st.cached_integrals(),"cached_coefficient_terms":st.cached_coefficient_terms(),"cached_coefficient_bytes":st.cached_coefficient_bytes()})}
}
