//! Validation-only moving-shell closure probe. No production owner is changed.
use std::{collections::{BTreeMap,BTreeSet},sync::Arc};
use symbolica::prelude::*;
use symbolica_amflow::finite_density::{DensityInput,guarded::{GuardedContext,GuardedMeasureIdentity,IndexBounds,IndexDomain,IndexRole},measure::WeightedMeasure};
use rustred::solver::{SearchOptions,guarded::{GuardedSource,GuardedSourceSystem,GuardedProgram,GuardedApplicationFailure,GuardedReductionLimits}};

type Sum<const N:usize> = BTreeMap<[i64;N],Atom>;
fn add<const N:usize>(out:&mut Sum<N>,i:[i64;N],c:Atom){let x=out.entry(i).or_default();*x=(&*x+c).expand().together().cancel();if x.is_zero(){out.remove(&i);}}
fn derivative<const N:usize>(i:[i64;N],flowing:&[usize])->Sum<N>{let mut out=Sum::new();for &s in flowing{if i[s]!=0{let mut j=i;j[s]+=1;add(&mut out,j,Atom::num(i[s]));}}out}
fn as_json<const N:usize>(s:&Sum<N>)->serde_json::Value{serde_json::json!(s.iter().map(|(i,c)|serde_json::json!({"indices":i.as_slice(),"coefficient":c.to_canonical_string()})).collect::<Vec<_>>())}
fn reduce<const N:usize>(p:&GuardedProgram<N>,s:&Sum<N>,admitted:&IndexDomain<N>,conditions:&mut BTreeSet<String>)->Result<Sum<N>,String>{
 let mut out=Sum::new();for (i,c) in s{let r=p.reduce(*i,GuardedReductionLimits{max_rule_applications:20000,max_pending_integrals:2048}).map_err(|e|e.to_string())?;
 for x in r.nonzero_conditions{conditions.insert(x.to_expression().to_canonical_string());}
 for (j,k) in r.terms{if !admitted.contains(&j){return Err(format!("terminal outside admitted domain {j:?}"));}add(&mut out,j,c*k.to_expression());}
 for t in r.unresolved{if !admitted.contains(&t.integral){return Err(format!("unresolved outside admitted domain {:?}",t.integral));}if t.reason!=GuardedApplicationFailure::NoApplicableRule{return Err(format!("explicit native application failure {:?} at {:?}",t.reason,t.integral));}add(&mut out,t.integral,c*t.coefficient.to_expression());}
 }Ok(out)
}
fn run<const N:usize>(cuts:&[usize],moving:bool,out:&std::path::Path){
 std::fs::create_dir_all(out).unwrap();let input:DensityInput=serde_json::from_str(&std::fs::read_to_string("examples/finite_density/massive_two_loop_sunset.json").unwrap()).unwrap();let prepared=input.prepare().unwrap();let family=prepared.occupied_cut(cuts,1000).unwrap().at_physical_masses();assert_eq!(family.factors().len(),N);
 let eta=symbol!("moving_sunset::eta");let ds=symbol!("moving_sunset::D");let d=Atom::var(ds);let e=Atom::var(eta);
 let indices=std::array::from_fn(|i|Symbol::parse(format!("moving_sunset::n{i}"),"moving_sunset").unwrap());let roles:[IndexRole;N]=family.roles().try_into().unwrap();
 let flowing=(0..family.physical_slots()).filter(|&i|moving||roles[i]==IndexRole::Ordinary).collect::<Vec<_>>();let mut factors=family.factors().to_vec();for &i in &flowing{factors[i]-=&e;}
 if moving{for sh in family.shells(){let energy=&family.coordinates()[3+sh.loop_index];let gram=&family.coordinates()[if sh.loop_index==0{0}else{2}];factors[sh.upper_slot]=(Atom::num(&sh.chemical_potential*&sh.chemical_potential)-&sh.mass_squared-energy*energy+gram).expand();}}
 let measure=WeightedMeasure::<N>::from_physical(family.coordinates().to_vec(),factors.clone(),roles.to_vec()).unwrap();
 let admitted=IndexDomain::new(std::array::from_fn(|s|if roles[s]==IndexRole::Occupation{IndexBounds::new(Some(0),None).unwrap()}else if s>=family.physical_slots()&&s<family.input_slots(){IndexBounds::new(None,Some(0)).unwrap()}else{IndexBounds::unbounded()})).unwrap();
 let mut identities=measure.lorentz_ibps(2,&d,&indices,256).unwrap();identities=identities.into_iter().filter_map(|mut row|{row.domain=row.domain.intersection(&admitted)?;Some(row)}).collect();
 let context=GuardedContext::new(GuardedMeasureIdentity{measure:format!("validation-only massive sunset; moving={moving}; factors={factors:?}; cuts={cuts:?}"),support:"real spatial balls radius²=mu²−m²=3/4, eta>0; all energy completion powers nonpositive; lower-contact empty support because each positive future shell mass² is 1/4+eta".into(),orientation:"future Minkowski shells; native virtual contours".into(),normalization:"native mixed loop measure; no numerical values in this closure probe".into(),branch:"positive real eta; continuation proved separately for small sunset; no general graph admission".into(),deformation:format!("D_i−eta on {flowing:?}; fixed spatial upper factor if moving; endpoint-correct Gamma_n target expansion with original converted coefficients held fixed")},roles,indices,vec![eta,ds],identities).unwrap();
 let original=context.sources();let rows=original.sources().iter().zip(original.native_sources().rows()).map(|(info,row)|GuardedSource::new(info.id.clone(),row.clone(),info.domain.clone()).with_nonzero_conditions(info.nonzero_conditions.clone())).collect();
 let zero_domains=family.shells().iter().map(|sh|IndexDomain::new(std::array::from_fn(|s|if s==sh.lower_slot{IndexBounds::new(Some(1),None).unwrap()}else if s==sh.physical_slot{IndexBounds::new(Some(1),None).unwrap()}else{admitted.bounds()[s]})).unwrap()).collect();
 let sources=Arc::new(GuardedSourceSystem::new(original.measure_id(),roles,*original.native_sources().index_variables(),rows).unwrap().with_zero_domains(zero_domains).unwrap());
 let mut targets=Vec::new();for target in family.targets(){let mut sum=Sum::<N>::new();for (label,c) in target{let mut terms=Sum::from([(std::array::from_fn(|s|i64::from(label.0[s])),c.clone())]);if moving{for sh in family.shells(){let mut expanded=Sum::new();for (i,c) in terms{assert!(i[sh.physical_slot]>0);add(&mut expanded,i,c.clone());for j in 1..i[sh.physical_slot]{let mut k=i;k[sh.physical_slot]-=j;k[sh.upper_slot]=j;add(&mut expanded,k,-&c/Atom::num(j));}}terms=expanded;}}for(i,c)in terms{add(&mut sum,i,c);}}targets.push(sum);}
 std::fs::write(out.join("definition.json"),serde_json::to_vec_pretty(&serde_json::json!({"moving":moving,"cuts":cuts,"factors":factors.iter().map(Atom::to_canonical_string).collect::<Vec<_>>(),"roles":format!("{roles:?}"),"flowing":flowing,"targets":targets.iter().map(as_json).collect::<Vec<_>>(),"source_count":sources.sources().len(),"measure_identity":sources.measure_id(),"target_interpolation":"fixed original inverse-propagator coefficients, Gamma_n expansion per occupied index; exact physical endpoint, numerator polynomial need not stay fixed for eta>0","budgets":{"rounds":6,"frontier":128,"native_domains_per_round":512,"native_max_depth":3,"rules":20000,"native_apply":20000,"pending":2048}})).unwrap()).unwrap();
 let mut frontier=targets.iter().flat_map(|t|t.keys().copied()).collect::<BTreeSet<_>>();let mut retained:Option<GuardedProgram<N>>=None;let mut conditions=BTreeSet::new();let mut history=Vec::new();let mut closed=None;let mut failure=None;
 for round in 0..6{let mut requested=frontier.clone();for i in &frontier{requested.extend(derivative(*i,&flowing).into_keys());}let requested=requested.into_iter().collect::<Vec<_>>();let domains=requested.iter().map(|i|IndexDomain::new(i.map(IndexBounds::fixed)).unwrap()).collect();
 let discovered=sources.solve_domains_with_priority_points(domains,&requested,SearchOptions{max_depth:Some(3),sample_seed:0,..Default::default()},512).unwrap();let gaps=discovered.unresolved.iter().map(|g|format!("{:?}: {}",g.reason,g.detail)).collect::<Vec<_>>();let fresh=GuardedProgram::new(sources.clone(),discovered.rules,[]).unwrap();let program=if let Some(previous)=retained{previous.union_replayed(fresh,[],20000).unwrap()}else{fresh};let before=frontier.clone();
 for i in &before{match reduce(&program,&derivative(*i,&flowing),&admitted,&mut conditions){Ok(s)=>frontier.extend(s.into_keys()),Err(e)=>{failure=Some(e);break;}}}
 history.push(serde_json::json!({"round":round,"requested":requested.len(),"frontier":frontier.iter().map(|i|i.as_slice()).collect::<Vec<_>>(),"rules":program.rules().len(),"gaps":gaps,"application_failure":failure}));std::fs::write(out.join("progress.json"),serde_json::to_vec_pretty(&history).unwrap()).unwrap();
 if failure.is_some(){break;}if frontier.len()>128{failure=Some("frontier budget exceeded; no closure claim".into());break;}
 if frontier==before{let audited=program.with_terminals_replayed(frontier.iter().copied(),20000).unwrap();let mut matrix=Vec::new();let mut weights=Vec::new();for i in &frontier{let s=reduce(&audited,&derivative(*i,&flowing),&admitted,&mut conditions).unwrap();assert!(s.keys().all(|j|frontier.contains(j)));matrix.push(serde_json::json!({"basis":i.as_slice(),"derivative":as_json(&s)}));}for t in &targets{let s=reduce(&audited,t,&admitted,&mut conditions).unwrap();assert!(s.keys().all(|j|frontier.contains(j)));weights.push(as_json(&s));}std::fs::write(out.join("closed.bin"),audited.encode_native(Default::default()).unwrap()).unwrap();closed=Some(serde_json::json!({"basis":frontier.iter().map(|i|i.as_slice()).collect::<Vec<_>>(),"matrix":matrix,"targets":weights,"rules":audited.rules().len()}));break;}
 retained=Some(program);
 }
 let result=serde_json::json!({"scope":"bounded native derivative-closure experiment only; no manual rules, values, boundaries, physical endpoint transport or production admission","moving":moving,"cuts":cuts,"closed":closed,"failure":failure,"history":history,"nonzero_conditions":conditions,"source_count":sources.sources().len()});std::fs::write(out.join("result.json"),serde_json::to_vec_pretty(&result).unwrap()).unwrap();println!("moving={moving} cuts={cuts:?} closed={} rounds={} failure={:?}",result["closed"].is_object(),result["history"].as_array().unwrap().len(),result["failure"]);
}
fn main(){let args=std::env::args().collect::<Vec<_>>();let out=std::path::Path::new(&args[1]);let moving=args[2]=="moving";match args[3].as_str(){"single"=>run::<7>(&[0],moving,out),"double"=>run::<9>(&[0,1],moving,out),_=>panic!("single/double")}}
