import pathlib,json,hashlib,gzip,collections
r=pathlib.Path(__file__).resolve().parent;h=lambda p:hashlib.sha256(p.read_bytes()).hexdigest();cases=[];point_changes=[]
for sector in ['single3','double']:
 a=json.loads((r/sector/'anchored/result.json').read_text());initial=json.loads((r/sector/'initial-checkpoint.json').read_text());assert initial['measure_id']==json.loads((r/sector/'input.json').read_text())['measure_id']
 for mode in ['anchored','fixed-cuts','fixed-cuts-and-occupations']:
  v=json.loads((r/sector/mode/'result.json').read_text());res=json.loads((r/sector/f'{mode}-resources.json').read_text());assert res['exit_code']==0;assert all(p['roundtrip']for p in v['probes'])and v['all_rhs_labels_admitted']
  changes=[]
  for i,(p,q)in enumerate(zip(a['probes'],v['probes'])):
   x,y=p['application'],q['application'];entry={'sector':sector,'mode':mode,'ordinal':i,'selection':p['selection'],'ray_status':q['ray']['status'],'point_fallback':q['point_fallback'],'final_status':y['status'],'rhs_terms':len(y['rhs']),'exact_rhs_equal_anchored':x['rhs']==y['rhs'],'ordered_conditions_equal_anchored':x['conditions']==y['conditions'],'rule_ordinal_changed':x['status']!=y['status'],'retained_rules':q['rules'],'unresolved_search_boxes':len(q['gaps'])}
   point_changes.append(entry)
  cases.append({'sector':sector,'mode':mode,'points':len(v['probes']),'source_count':v['source_count'],'ray_statuses':dict(collections.Counter(x['ray']['status']for x in v['probes'])),'fallbacks':sum(x['point_fallback']for x in v['probes']),'final_applicable':sum(x['application']['status'].startswith('Applied')for x in v['probes']),'final_unresolved':sum(x['application']['status'].startswith('Unresolved')for x in v['probes']),'rhs_terms':sum(len(x['application']['rhs'])for x in v['probes']),'total_rules_across_independent_programs':sum(x['rules']for x in v['probes']),'exact_rhs_equal_anchored':all(p['application']['rhs']==q['application']['rhs']for p,q in zip(a['probes'],v['probes'])),'ordered_conditions_equal_anchored':all(p['application']['conditions']==q['application']['conditions']for p,q in zip(a['probes'],v['probes'])),'resources':{'path':f'{sector}/{mode}-resources.json','sha256':h(r/sector/f'{mode}-resources.json'),'wall_seconds':res['wall_seconds'],'peak_child_rss_kib':res['peak_child_rss_kib']}})
archives=[]
for p in sorted(r.glob('*/*/point-*.bin')):
 raw=p.read_bytes();dest=pathlib.Path(str(p)+'.gz');assert not dest.exists();compressed=gzip.compress(raw,compresslevel=9,mtime=0);dest.write_bytes(compressed);assert gzip.decompress(dest.read_bytes())==raw
 archives.append({'logical_path':str(p.relative_to(r)),'stored_path':str(dest.relative_to(r)),'raw_bytes':len(raw),'stored_bytes':len(compressed),'raw_sha256':hashlib.sha256(raw).hexdigest(),'stored_sha256':h(dest),'roundtrip_verified':True});p.unlink()
if not archives and (r/'archives.json').exists():archives=json.loads((r/'archives.json').read_text())['files']
(r/'archives.json').write_text(json.dumps({'schema':'lossless-gzip-restore-map-v1','gzip_mtime':0,'files':archives},indent=2)+'\n')
out={'scope':'Discovery query-domain presentation only; unchanged source corpus, admitted role domains, zero evidence, native ordering, search seed and depth. No rules imported into fresh discovery.','budgets':{'depth':3,'ray_domains_per_label':1,'point_domains_per_label':1,'timeout_seconds_per_arm':300},'selection':'Complete actual initial round000 requested lists plus seven previous depth-control labels, deduplicated:64 single3 and35 double. Original exact source measure identities match initial/current checkpoints.','cases':cases,'points':point_changes,'roundtrip_programs':297,'result':'All297 rays return NoApplicableRule at cap1 and require exact-point fallback. Fixing cuts or cuts+occupations changes no final RHS or ordered condition list. Single3 is64 Applied; double31 Applied/4NoRule for every policy.','limits':'This is a one-domain ray allocation result, not proof that fixed-role symbolic rays cannot help at larger budgets. Rule ordinals can move because unused ray rules precede the same point rule. No coverage, period or full-family closure claim.','performance_scope':'Shared host, two concurrent sectors, historical selection replay included. No timing superiority claim.'}
(r/'summary.json').write_text(json.dumps(out,indent=2)+'\n')
(r/'README.md').write_text('Fixing required-cut indices, or fixing both cut and occupation indices, does not improve ray coverage at the tested one-domain allocation. All297 queries still need exact-point fallback. Final RHS maps and ordered nonzero conditions are identical to fully anchored rays. Single3 retains64 applicable results and844 RHS terms; double retains31 applicable results,4 explicit NoRule results and307 RHS terms.\n\nThe sample includes every actual initial round000 request plus the seven earlier targeted depth labels:64 single3 and35 double labels after deduplication. Initial and later checkpoint source identities are checked exactly. The historical program is replayed only to validate previous leaf/control selections and record initial statuses, then discarded. Native discovery remains the only reducer; no previous rules or numerical references enter it.\n\nEvery arm uses the same original sources, role admission, zeros, coordinate order, sample seed0, depth3, ray cap1 and exact-point fallback cap1. The only difference is the ray box: all nonzero coordinates anchored; or required cuts fixed; or required cuts and occupations fixed. Ordinary coordinates always retain their anchored symbolic powers. All297 encoded programs independently decode/replay with admitted RHS labels, including the12 programs whose requested point remains explicitly unresolved. Search gaps are retained.\n\nFixed-role rays sometimes add an unused rule, so the applicable point rule can move from ordinal0 to1. Rule totals across independent programs increase64→68 for single3 and31→40/43 for double; this is not a coverage gain. These results do not rule out different domain budgets, but provide no reason to enable fixed-role rays under the tested allocation. Shared-host timings include historical replay and are not a performance comparison.\n\nAll point proof binaries are deterministically gzipped with mtime0 and byte-exact roundtrip verification; archives.json maps their original logical paths and hashes. Input source binaries remain raw. See summary.json for exact counts/conditions comparisons and the per-arm result files for full proof source traces and uncovered domains.\n')
files=[p for p in sorted(r.rglob('*'))if p.is_file()and p.name!='manifest.json'];(r/'manifest.json').write_text(json.dumps({'schema':'sha256-file-manifest-v1','files':[{'path':str(p.relative_to(r)),'bytes':p.stat().st_size,'sha256':h(p)}for p in files]},indent=2)+'\n');print('files',len(files),'manifest',h(r/'manifest.json'),'archive_count',len(archives),'raw_bytes',sum(x['raw_bytes']for x in archives),'stored_bytes',sum(x['stored_bytes']for x in archives))
